#import "@preview/ilm:1.4.0": *
#show: ilm.with(
  title: [
    PHYS 158 Study Notes \
    #underline[Electricity and Magnetism]
  ],
  author: "Yecheng Liang",
)

#import "@preview/cetz:0.3.1": canvas, draw
#import "@preview/cetz-plot:0.1.0": plot

#import "@preview/physica:0.9.4": *
#import "@preview/metro:0.3.0": *
#import units: *
#import prefixes: *

= DC Circuits

== Basic Components
/ Power Supplies (DC/AC): Direct Current and Alternating Current.

/ Resistors (R): Resists current, consumes power.
  Light bulbs, lamps are also resistors.

/ #link(<sc:capacitor>)[Capacitors (C)]: Stores electric charge and energy.
  Not to be confused with batteries: \
  Batteries release energy in a slow manner;
  capacitors can discharge energy in a short burst.

/ Inductors/Stabilizers (L): Generates induced current, opposing passing current.

== Current, Voltage, Capacitance, and Resistance
/ Charge (Q): The amount of electric charge, measured in Coulombs (C).

/ Current (I): The flow of electric charge, $I = dd(Q) / dd(t)$, measured in Amperes (A).
  It is generated by a voltage difference.

/ Voltage (V): The potential difference between two points, measured in Volts (V).

/ #link(<sc:capacitance>)[Capacitance (C)]: The ability to store electric charge, measured in Farads (F).

/ Resistance (R): The opposition to the flow of electric current, measured in Ohms ($Omega$).
  $ V = I R $

  Resistance of a resistor depends on its material, length $L$, and cross-sectional area $A$.
  $ R = rho L / A $ where $rho$ is the resistivity of the material.

  For multiple resistors,
  $ R_"series" = R_1 + R_2 + ... $
  $ 1 / R_"parallel" = 1 / R_1 + 1 / R_2 + ... $

== Voltage Drops
/ Electromotive Force (EMF): The voltage difference between the positive and negative terminals of a DC power supply (battery) is $V "or" epsilon$, specified on the battery.

/ Resistance: The voltage drop across a resistor is $ Delta V_R = I R $.

/ Capacitance: The voltage drop across a capacitor is $ Delta V_C = Q / C $ where $C$ is the capacitance.

/ Inductance: The voltage drop across an inductor is $ Delta V_L = -L dd(I) / dd(t) $ where $L$ is the inductance.

== Reading Resistors
There will be maximum 5 color bands on a resistor.
From the left to the right:
- 1-3: The first three digits of the resistance value.
- 4: The number of zeros following the first three digits (multiplier).
- 5: The tolerance of the resistance value.

Sometimes, there will be 4 bands only, where there are only 2 digits represented, followed by the number of zeros.

#let res-digit-colors = (
  "0": black,
  "1": orange.darken(50%), // brown
  "2": red,
  "3": orange,
  "4": yellow,
  "5": green,
  "6": blue,
  "7": purple,
  "8": color.gray,
  "9": white,
)

#let res-tolerance-colors = (
  "5": yellow.transparentize(50%), // gold
  "10": silver,
)

#figure(
  caption: [Resistor digit colors],
  grid(
    columns: res-digit-colors.len(),
    stroke: 0.5pt,
    inset: 0.8em,
    ..for (d, c) in res-digit-colors {
      (grid.cell(fill: c, text(font: "Fira Mono", stroke: 0.8pt + yellow, size: 2em, d)),)
    }
  ),
)

#figure(
  caption: [Resistor tolerance colors],
  grid(
    columns: res-tolerance-colors.len(),
    stroke: 0.5pt,
    inset: 0.8em,
    ..for (d, c) in res-tolerance-colors {
      (grid.cell(fill: c, text(font: "Fira Mono", stroke: 0.8pt + yellow, size: 2em, d + "%")),)
    }
  ),
)

== Kirchhoff's Laws
When traveling in the direction of the current, the voltage change through a resistor is negative, $Delta V = -I R$, and positive through a battery, $Delta V = +epsilon$.
When traveling against the direction of the current, invert the signs.

/ Kirchhoff's Current Law (KCL): The sum of currents entering a node is equal to the sum of currents leaving the node.
  $ Sigma I_"in" = Sigma I_"out" $

/ Kirchhoff's Voltage Law (KVL): The sum of voltage drops in a closed loop is equal to the sum of voltage rises.
  $ Sigma V_"drop" = Sigma V_"rise" $
  A 'closed loop' is a path that starts and ends at the same point, no matter the direction of current.

These two laws are crucial in analyzing circuits (solving problems), especially when appliances are not clearly connected in series or parallel.

== Short, Open Circuits and Proportionality
/ Short Circuit: A circuit with no resistance, causing a large current to flow.
  The voltage drop across a short circuit is zero.
/ Open Circuit: A circuit with infinite resistance, causing no current to flow.

In case of a parallel circuit, the voltage across each component is the same, while the current is inversely proportional to the resistance.
While in a series circuit, the current across each component is the same, while the voltage is inversely proportional to the resistance.

For instance, $qty(3, A)$ of current flows through a $qty(2, "Omega")$ and a $qty(1, "Omega")$ resistors, the current through each will be $qty(1, A) "and" qty(2, A)$.

Combining this knowledge with Kirchhoff's laws, we can solve even more complex circuits.

== Real Batteries
/ Internal Resistance ($r$): The resistance within a battery, causing a voltage drop.
  $
    V_"battery" &= epsilon - I r \
    I &= epsilon / (r + R).
  $

Hence, the terminal voltage of a battery is
$
  V_"terminal" &= epsilon - epsilon / (r + R) r \
  &= epsilon R / (r + R).
$

== Power
/ Power: The rate at which energy is consumed or produced, measured in Watts ($unit(W)$).
  $ P = I V = I^2 R = V^2 / R $

== Grounding
/ Ground: A reference point in a circuit, usually at zero voltage.
  It is used to measure the voltage of other points in the circuit.

/ Grounding: Connecting a circuit to the ground or other big conductors to send away excess energy, usually to prevent electric shock.
  It is also used to stabilize the voltage of a circuit.

Addition of a ground symbol in a circuit diagram does not affect the circuit itself, our calculations stay the same.
However, our *zero reference point changes*, and we must measure the voltage of other points in the circuit with respect to the ground!

== Capacitor <sc:capacitor>
Any collection of conductors that can store electric charge & energy.

== Capacitance ($C$) <sc:capacitance>
The ability to store electric charge, measured in Farads ($unit(F)$).

$
  C = Q / V.
$

Capacitance of a capacitor depends on its material, area $A$, and distance $d$ between plates.
$ C = epsilon A / d $ where $epsilon$ is the electric permittivity of the material.

$ Q = C V $
$ I = dd(Q) / dd(t) = C dd(V) / dd(t) $

For multiple capacitors,
$ C_"series" = 1 / (1 / C_1 + 1 / C_2 + ...) $ <eq:capacitor-series>
$ C_"parallel" = C_1 + C_2 + ... $ <eq:capacitor-parallel>

=== Capacitors in Parallel
As they are in parallel, the voltage drop across them should be the same, regardless of the capacitance.
$
  V &= V_1 = V_2 = ... \
  Q &= C_1 V_1 + C_2 V_2 + ... \
  &= C_1 V + C_2 V + ... \
  &= (C_1 + C_2 + ...) V \
  Q / V &= C_1 + C_2 + ...
$ which leads to @eq:capacitor-parallel.

Imagine all the parallel capacitors as one big capacitor with the sum of capacitances. Now the formula makes sense.

=== Capacitors in Series
When connected in series, the capacitors can be viewed as one beginning plate with positive charges and one ending plate with negative charges, plus all the plates in between, with charges but adding up to zero.

In this case, charges across the capacitors are the same.
$
  Q &= Q_1 = Q_2 = ... \
  V &= V_1 + V_2 + ... \
  &= Q / C_1 + Q / C_2 + ... \
  &= Q (1 / C_1 + 1 / C_2 + ...) \
  V / Q &= 1 / C_1 + 1 / C_2 + ...
$ which leads to @eq:capacitor-series.

=== Work and Energy in Capacitors
Batteries charge capacitors bit by bit, by $dd(q)$.
Thus, we can say the work done is
$
  dd(W) &= Delta V dd(q) \
  &= q / C dd(q) \
$
And energy is
$
  U &= 1 / C integral_0^Q q dd(q) = Q^2 / (2 C) \
  &= (C V^2) / 2.
$ <eq:capacitor-energy>

=== Energy in C-only Circuits
It seems curious that, in a circuit with only capacitors, when charge is transferred between capacitors, the energy is _not_ conserved, in other word, lost.

That is because capacitor behaviors cannot be examined without resistors, so even if not shown, the circuit should contain some resistance, probably in the wires.

=== R-C Circuits
/ R-C Circuits: Circuits with resistors and capacitors.
  They are used in timing circuits, filters, and oscillators.

Imagine a circuit with a battery, a switch, a resistor and a capacitor.
The capacitor initially has no charge, and the switch is closed at $t = 0$.

+ At $t = 0-$, the capacitor has no charge, and the voltage across it is zero.
+ At $t = 0+$, the switch is _just_ closed, and the capacitor starts charging. The voltage across the capacitor is still zero since it has no charge, and hence act as an ideal wire.
+ As time goes by, the capacitor charges, and the voltage across it increases, while the current decreases.
+ At $t -> oo$, the capacitor is fully charged, and it act as an open circuit, and the current is zero.

By Kirchhoff's Voltage Law, the voltage across the resistor and the capacitor should sum up to the battery voltage.
$
  V_"battery" &= V_"resistor" + V_"capacitor" \
  &= i(t) R + q(t) / C.
$
As $i(t) = dv(q, t)$, we can rewrite the equation as
$
  epsilon = R dv(q, t) + q / C.
$ <eq:voltage-rc>

Derive the @eq:voltage-rc in respect to time, we get
$
  dv(epsilon, t) &= R dv(q(t), t, 2) + dv(q(t), t) / C \
  0 &= R dv(i(t), t) + i(t) / C.
$

=== Charging and Discharging Capacitors
When a capacitor is charging, the current flows from the battery to the capacitor, and the voltage across the capacitor increases.
When a capacitor is discharging, the current flows from the capacitor to the circuit, and the voltage across the capacitor decreases.

In an R-C circuit, the energy stored in the capacitor increases and decreases exponentially, respectively.
#let q-charge = t => 1 - calc.exp(-t / 2)
#let q-discharge = t => calc.exp(-t / 2)
$
  q(t)_"charging" &= C V (1 - e^(-t slash R C)) \
  i(t)_"charging" &= dv(q(t), t) = V / R e^(-t slash R C),
$ $C V$ is the final charge that would be stored in the capacitor.

$
  q(t)_"discharging" &= Q_0 e^(-t slash R C) \
  i(t)_"discharging" &= dv(q(t), t) = I_0 e^(-t slash R C).
$ where $Q$ is the maximum charge stored in the capacitor, $R$ is the resistance in series, and $C$ is the capacitance in parallel.

#let plot-options = (
  axis-style: "left",
  size: (8, 4),
  x-label: $t$,
  y-label: $q$,
  x-tick-step: none,
  y-tick-step: none,
  x-ticks: (),
  y-ticks: (),
)
#let dash-stroke = (dash: "dashed", thickness: .5pt, paint: black.transparentize(75%))

#figure(
  canvas({
    import draw: *

    plot.plot(
      name: "f",
      ..plot-options,
      {
        plot.add(q-charge, domain: (0, 8))
        plot.add-anchor("charging-tau", (2, q-charge(2)))

        plot.add(q-discharge, domain: (0, 8))
        plot.add-anchor("discharging-tau", (2, q-discharge(2)))
      },
    )

    circle("f.charging-tau", radius: 1pt)
    line((), (rel: (0, -q-charge(2) * 4)), stroke: dash-stroke)
    content((rel: (0, -.25)), $tau$)
    line("f.charging-tau", (rel: (-2, 0)), stroke: dash-stroke)
    content((rel: (-1, 0)), box(width: 10em, $1 - e^(-1) = 63.2%$))

    circle("f.discharging-tau", radius: 1pt)
    line("f.discharging-tau", (rel: (-2, 0)), stroke: dash-stroke)
    content((rel: (-1, 0)), box(width: 7em, $e^(-1) = 36.8%$))
  }),
)



At times, $R C$ is written as $tau$, the time constant of the RC circuit.
Think: at $t = tau$, how much charge is in the capacitor?

Notice the similarity between these equations and the exponential decay equation for damped oscillations, it will be useful.


== Inductors
/ Inductors: A coil of wire that generates an induced current, opposing the passing current.
  They are used in transformers, motors, and generators.
/ Inductance ($L$): The ability to generate an induced current, measured in Henrys ($unit(H)$).
  $ V = L dd(I) / dd(t) $

Inductors act quite as an opposite to capacitors, consider the prior switch-closed capacitor example:
+ At $t = 0-$, the current is zero, and the voltage across the inductor is zero.
+ At $t = 0+$, the switch is _just_ closed, the voltage across the inductor is $epsilon$ as there is still no current so potential drop across other components (resistor) is zero.
+ As time goes by, the current increases, and the voltage across the inductor decreases.
+ At $t -> oo$, the current is at maximum and constant, and the voltage across the inductor is zero.

$
  i(t)_"charging" &= I_"max" (1 - e^(-R t slash L)) \
  i(t)_"discharging" &= I_"max" e^(-R t slash L).
$

It is more important to know the shape of the graphs: exponential growth and decay, rather than the steps seen in R-only circuits.

Given the current and inductance, the energy stored in the inductor is
$
  U = 1 / 2 L I^2.
$

=== R-L-C Circuits
In an R-L-C circuit, the function for current reminds us of the damped oscillations equation.
So recall the damped oscillations equation:
$
  x(t) = A e^(-t / tau) cos(omega' t + phi)
$ where $A$ is the amplitude, $tau$ is the time constant, $omega'$ is the angular frequency, and $phi$ is the phase angle.
(On formula sheet.)

#figure(
  canvas({
    import draw: *
    plot.plot(
      name: "f",
      ..plot-options + (axis-style: "school-book"),
      {
        plot.add(t => calc.exp(-t / 3) * calc.cos(2 * calc.pi * t), domain: (0, calc.pi * 3), samples: 300)
      },
    )
  }),
)


= AC Circuits
You should still read the DC Circuits section before this one.

/ Root Mean Square (RMS): The square root of the mean of the squares of a set of values.
  For example, the RMS current is the current that would produce the same amount of heat in a resistor as the alternating current which is being derived from.

== Voltage and Current in AC
$
  V(t) = V_"max" sin(omega t).
$

$
  V_"rms" &= V_"max" / sqrt(2) \
  I_"rms" &= I_"max" / sqrt(2).
$
This can be deduced from $sin(omega t) = 1/2 (1 - cos(2omega t))$.

On an oscilloscope, the "Amplitude" will be double the RMS value, since it is measuring the peak-to-trough value.

== R Circuit
$
  i(t) &= V(t) / R \
  &= V_"max" / R sin(omega t),
$ in phase with the voltage.
At times, $R$ is written as $X_R$, the resistance.

== L Circuit
$
  V(t) &= L dv(i,t) \
  dv(i,t) &= V(t) / L \
  &= V_"max" / L sin(omega t), \
  i(t) &= - V_"max" / (omega L) cos(omega t) \
  &= V_"max" / (omega L) cos(omega t - pi / 2) \
  &= I_"max" sin(omega t - pi / 2),
$ out of phase with the voltage.
At times, $omega L$ is written as $X_L$, the inductive reactance.

Note that $X_L &-> 0 "as" omega -> 0, X_L &-> oo "as" omega -> oo.$

== C Circuit
$
  q(t) &= C V(t) \
  i(t) &= dv(q,t) \
  &= (omega C) V_"max" cos(omega t) \
  &= (V_"max" omega C) sin(omega t + pi / 2) \
  &= I_"max" sin(omega t + pi / 2),
$ out of phase with the voltage.
At times, $1 slash (omega C)$ is written as $X_C$, the capacitive reactance.

Note that $X_C &-> oo "as" omega -> 0, X_C &-> 0 "as" omega -> oo.$

== Phasors
Phasors are vectors that represent the amplitude and phase of a sinusoidal function.

#figure(
  caption: [Phasor diagram],
  image("assets/phasor.png", width: 67%)
)

Using projection,
$
  i(t) &= I_"max" cos(omega t) \
  v(t) &= V_"max" cos(omega t + phi).
$

$
  tan(phi) = (X_L - X_C) / X_R
$ is the phase angle between the current and the _source_ voltage.

#figure(
  caption: [Phasor diagram for R-L-C circuits],
  image("assets/phasors-rlc.png", width: 50%)
)

== Impedance
/ Impedance ($Z$): The total opposition to the flow of current in an AC circuit, measured in Ohms ($unit("Omega")$).
It is the combination of resistance, inductive reactance, and capacitive reactance.

From the phasor diagram it is clear that, using Pythagoras' theorem,
$
  Z &= sqrt(X_R^2 + (X_L - X_C)^2) \
  &= sqrt(R^2 + (omega L - 1 / (omega C))^2).
$

Like Ohm's Law, we can write
$
  V_"max" = I_"max" Z.
$

== R-L-C Circuits
If $X_L > X_C$, the current phasor is behind the voltage phasor, and the circuit is inductive.
$
  i(t) &= I_"max" cos(omega t) \
  v(t) &= V_"max" cos(omega t + phi).
$

If $X_L < X_C$, the current phasor is ahead of the voltage phasor, and the circuit is capacitive.
$
  i(t) &= I_"max" cos(omega t) \
  v(t) &= V_"max" cos(omega t - abs(phi)).
$

== Power Dissipation
In DC circuits, power is $P = I V$ as we all know it.
Similarly, $P$ is kind of the same in AC circuits, but we need to consider the phase difference between the current and voltage.
$
  angle.l P angle.r = angle.l i(t) v(t) angle.r
$

In R-L-C circuits,
$
  angle.l P angle.r = (V_"peak" I_"peak") / 2 cos(phi)
$ with $V_"peak" I_"peak"$ replaceable with anything equivalent.
