#import "@preview/ilm:1.4.0": *
#show: ilm.with(
  title: [
    PHYS 158 Study Notes \
    #underline[Electricity and Magnetism]
  ],
  author: "Yecheng Liang",
)

#import "@preview/circuiteria:0.1.0": *

#import "@preview/physica:0.9.4": *
#import "@preview/metro:0.3.0": *
#import units: *
#import prefixes: *

= Circuits

== Basic Components
/ Power Supplies (DC/AC): Direct Current and Alternating Current.

/ Resistors (R): Resists current, consumes power.
  Light bulbs, lamps are also resistors.

/ #link(<sc:capacitor>)[Capacitors (C)]: Stores electric charge and energy.
  Not to be confused with batteries: \
  Batteries release energy in a slow manner;
  capacitors can discharge energy in a short burst.

/ Inductors/Stabilizers (L): Generates induced current, opposing passing current.

== Current, Voltage, Capacitance, and Resistance
/ Charge (Q): The amount of electric charge, measured in Coulombs (C).

/ Current (I): The flow of electric charge, $I = dd(Q) / dd(t)$, measured in Amperes (A).
  It is generated by a voltage difference.

/ Voltage (V): The potential difference between two points, measured in Volts (V).

/ #link(<sc:capacitance>)[Capacitance (C)]: The ability to store electric charge, measured in Farads (F).

/ Resistance (R): The opposition to the flow of electric current, measured in Ohms ($Omega$).
  $ V = I R $

  Resistance of a resistor depends on its material, length $L$, and cross-sectional area $A$.
  $ R = rho L / A $ where $rho$ is the resistivity of the material.

  For multiple resistors,
  $ R_"series" = R_1 + R_2 + ... $
  $ 1 / R_"parallel" = 1 / R_1 + 1 / R_2 + ... $

== Voltage Drops
/ Electromotive Force (EMF): The voltage difference between the positive and negative terminals of a DC power supply (battery) is $V "or" epsilon$, specified on the battery.

/ Resistance: The voltage drop across a resistor is $ Delta V_R = I R $.

/ Capacitance: The voltage drop across a capacitor is $ Delta V_C = Q / C $ where $C$ is the capacitance.

/ Inductance: The voltage drop across an inductor is $ Delta V_L = -L dd(I) / dd(t) $ where $L$ is the inductance.

== Reading Resistors
There will be maximum 5 color bands on a resistor.
From the left to the right:
- 1-3: The first three digits of the resistance value.
- 4: The number of zeros following the first three digits (multiplier).
- 5: The tolerance of the resistance value.

Sometimes, there will be 4 bands only, where there are only 2 digits represented, followed by the number of zeros.

#let res-digit-colors = (
  "0": black,
  "1": orange.darken(50%), // brown
  "2": red,
  "3": orange,
  "4": yellow,
  "5": green,
  "6": blue,
  "7": purple,
  "8": color.gray,
  "9": white,
)

#let res-tolerance-colors = (
  "5": yellow.transparentize(50%), // gold
  "10": silver,
)

#figure(
  caption: [Resistor digit colors],
  grid(
    columns: res-digit-colors.len(),
    stroke: 0.5pt,
    inset: 0.8em,
    ..for (d, c) in res-digit-colors {
      (grid.cell(fill: c, text(font: "Fira Mono", stroke: 0.8pt + yellow, size: 2em, d)),)
    }
  ),
)

#figure(
  caption: [Resistor tolerance colors],
  grid(
    columns: res-tolerance-colors.len(),
    stroke: 0.5pt,
    inset: 0.8em,
    ..for (d, c) in res-tolerance-colors {
      (grid.cell(fill: c, text(font: "Fira Mono", stroke: 0.8pt + yellow, size: 2em, d + "%")),)
    }
  ),
)

== Kirchhoff's Laws
When traveling in the direction of the current, the voltage change through a resistor is negative, $Delta V = -I R$, and positive through a battery, $Delta V = +epsilon$.
When traveling against the direction of the current, invert the signs.

/ Kirchhoff's Current Law (KCL): The sum of currents entering a node is equal to the sum of currents leaving the node.
  $ Sigma I_"in" = Sigma I_"out" $

/ Kirchhoff's Voltage Law (KVL): The sum of voltage drops in a closed loop is equal to the sum of voltage rises.
  $ Sigma V_"drop" = Sigma V_"rise" $
  A 'closed loop' is a path that starts and ends at the same point, no matter the direction of current.

These two laws are crucial in analyzing circuits (solving problems), especially when appliances are not clearly connected in series or parallel.

== Short, Open Circuits and Proportionality
/ Short Circuit: A circuit with no resistance, causing a large current to flow.
  The voltage drop across a short circuit is zero.
/ Open Circuit: A circuit with infinite resistance, causing no current to flow.

In case of a parallel circuit, the voltage across each component is the same, while the current is inversely proportional to the resistance.
While in a series circuit, the current across each component is the same, while the voltage is inversely proportional to the resistance.

For instance, $qty(3, A)$ of current flows through a $qty(2, "Omega")$ and a $qty(1, "Omega")$ resistors, the current through each will be $qty(1, A) "and" qty(2, A)$.

Combining this knowledge with Kirchhoff's laws, we can solve even more complex circuits.

== Real Batteries
/ Internal Resistance ($r$): The resistance within a battery, causing a voltage drop.
  $
    V_"battery" &= epsilon - I r \
    I &= epsilon / (r + R).
  $

Hence, the terminal voltage of a battery is
$
  V_"terminal" &= epsilon - epsilon / (r + R) r \
  &= epsilon R / (r + R).
$

== Power
/ Power: The rate at which energy is consumed or produced, measured in Watts ($unit(W)$).
  $ P = I V = I^2 R = V^2 / R $

== Grounding
/ Ground: A reference point in a circuit, usually at zero voltage.
  It is used to measure the voltage of other points in the circuit.

/ Grounding: Connecting a circuit to the ground or other big conductors to send away excess energy, usually to prevent electric shock.
  It is also used to stabilize the voltage of a circuit.

Addition of a ground symbol in a circuit diagram does not affect the circuit itself, our calculations stay the same.
However, our *zero reference point changes*, and we must measure the voltage of other points in the circuit with respect to the ground!

== Capacitor <sc:capacitor>
Any collection of conductors that can store electric charge & energy.

== Capacitance ($C$) <sc:capacitance>
The ability to store electric charge, measured in Farads ($unit(F)$).

$
  C = Q / V.
$

Capacitance of a capacitor depends on its material, area $A$, and distance $d$ between plates.
$ C = epsilon A / d $ where $epsilon$ is the electric permittivity of the material.

$ Q = C V $
$ I = dd(Q) / dd(t) = C dd(V) / dd(t) $

For multiple capacitors,
$ C_"series" = 1 / (1 / C_1 + 1 / C_2 + ...) $ <eq:capacitor-series>
$ C_"parallel" = C_1 + C_2 + ... $ <eq:capacitor-parallel>

=== Capacitors in Parallel
As they are in parallel, the voltage drop across them should be the same, regardless of the capacitance.
$
  V &= V_1 = V_2 = ... \
  Q &= C_1 V_1 + C_2 V_2 + ... \
  &= C_1 V + C_2 V + ... \
  &= (C_1 + C_2 + ...) V \
  Q / V &= C_1 + C_2 + ...
$ which leads to @eq:capacitor-parallel.

Imagine all the parallel capacitors as one big capacitor with the sum of capacitances. Now the formula makes sense.

=== Capacitors in Series
When connected in series, the capacitors can be viewed as one beginning plate with positive charges and one ending plate with negative charges, plus all the plates in between, with charges but adding up to zero.

In this case, charges across the capacitors are the same.
$
  Q &= Q_1 = Q_2 = ... \
  V &= V_1 + V_2 + ... \
  &= Q / C_1 + Q / C_2 + ... \
  &= Q (1 / C_1 + 1 / C_2 + ...) \
  V / Q &= 1 / C_1 + 1 / C_2 + ...
$ which leads to @eq:capacitor-series.

=== Work and Energy in Capacitors
Batteries charge capacitors bit by bit, by $dd(q)$.
Thus, we can say the work done is
$
  dd(W) &= Delta V dd(q) \
  &= q / C  dd(q) \
$
And energy is
$
  U &= 1 / C integral_0^Q q dd(q) = Q^2 / (2 C) \
  &= (C V^2) / 2.
$ <eq:capacitor-energy>

=== Energy in C-only Circuits
It seems curious that, in a circuit with only capacitors, when charge is transferred between capacitors, the energy is _not_ conserved, in other word, lost.

That is because capacitor behaviors cannot be examined without resistors, so even if not shown, the circuit should contain some resistance, probably in the wires.

=== R-C Circuits
/ R-C Circuits: Circuits with resistors and capacitors.
  They are used in timing circuits, filters, and oscillators.

Imagine a circuit with a battery, a switch, a resistor and a capacitor.
The capacitor initially has no charge, and the switch is closed at $t = 0$.

1. At $t = 0-$, the capacitor has no charge, and the voltage across it is zero.
2. At $t = 0+$, the switch is _just_ closed, and the capacitor starts charging. The voltage across the capacitor is still zero since it has no charge, and hence act as an ideal wire.
3. As time goes by, the capacitor charges, and the voltage across it increases, while the current decreases.

By Kirchhoff's Voltage Law, the voltage across the resistor and the capacitor should sum up to the battery voltage.
$
  V_"battery" &= V_"resistor" + V_"capacitor" \
  &= i(t) R + q(t) / C.
$
As $i(t) = dv(q, t)$, we can rewrite the equation as
$
  epsilon = R dv(q, t) + q / C.
$ <eq:voltage-rc>

Derive the @eq:voltage-rc in respect to time, we get
$
  dv(epsilon, t) &= R dv(q(t), t, 2) + dv(q(t), t) / C \
  0 &= R dv(i(t), t) + i(t) / C.
$

=== Charging and Discharging Capacitors
When a capacitor is charging, the current flows from the battery to the capacitor, and the voltage across the capacitor increases.
When a capacitor is discharging, the current flows from the capacitor to the circuit, and the voltage across the capacitor decreases.

In an R-C circuit, the energy stored in the capacitor increases and decreases exponentially, respectively.
$
  q(t)_"charging" &= Q (1 - e^(-t slash R C)) \
  i(t)_"charging" &= dv(q(t), t) = e^(-t slash R C) / (R C),
$ $
  q(t)_"discharging" &= Q e^(-t slash R C) \
  i(t)_"discharging" &= dv(q(t), t) = - e^(-t slash R C) / (R C)
$ where $Q$ is the maximum charge stored in the capacitor, $R$ is the resistance in series, and $C$ is the capacitance in parallel.

At times, $R C$ is written as $tau$, the time constant of the RC circuit.
Think: at $t = tau$, how much charge is in the capacitor?

Notice the similarity between these equations and the exponential decay equation for damped oscillations, it will be useful.
