#import "@preview/ilm:1.4.0": *
#show: ilm.with(
  title: [
    PHYS 158 Study Notes \
    #underline[Electricity and Magnetism]
  ],
  author: "Yecheng Liang",
)

#import "@preview/circuiteria:0.1.0": *

#import "@preview/physica:0.9.4": *
#import "@preview/metro:0.3.0": *
#import units: *
#import prefixes: *

= Circuits

== Basic Components
/ Power Supplies (DC/AC): Direct Current and Alternating Current.

/ Resistors (R): Resists current, consumes power.
  Light bulbs, lamps are also resistors.

/ Capacitors (C): Stores electric charge and energy.
  Not to be confused with batteries: \
  Batteries release energy in a slow manner;
  capacitors can discharge energy in a short burst.

/ Inductors/Stabilizers (L): Generates induced current, opposing passing current.

== Current, Voltage, Capacitance, and Resistance
/ Charge (Q): The amount of electric charge, measured in Coulombs (C).

/ Current (I): The flow of electric charge, $I = dd(Q) / dd(t)$, measured in Amperes (A).
  It is generated by a voltage difference.

/ Voltage (V): The potential difference between two points, measured in Volts (V).

/ Capacitance (C): The ability to store electric charge, measured in Farads (F).
  $ Q = C V $
  $ I = dd(Q) / dd(t) = C dd(V) / dd(t) $

  Capacitance of a capacitor depends on its material, area $A$, and distance $d$ between plates.
  $ C = epsilon A / d $ where $epsilon$ is the permittivity of the material.

  For multiple capacitors,
  $ C_"series" = 1 / (1 / C_1 + 1 / C_2 + ...) $
  $ C_"parallel" = C_1 + C_2 + ... $

/ Resistance (R): The opposition to the flow of electric current, measured in Ohms ($Omega$).
  $ V = I R $
  $ P = I V = I^2R = V^2 / R $

  Resistance of a resistor depends on its material, length $L$, and cross-sectional area $A$.
  $ R = rho L / A $ where $rho$ is the resistivity of the material.

  For multiple resistors,
  $ R_"series" = R_1 + R_2 + ... $
  $ 1 / R_"parallel" = 1 / R_1 + 1 / R_2 + ... $

== Voltage Drops
/ Electromotive Force (EMF): The voltage difference between the positive and negative terminals of a DC power supply (battery) is $V "or" epsilon$, specified on the battery.

/ Resistance: The voltage drop across a resistor is $ Delta V_R = I R $.

/ Capacitance: The voltage drop across a capacitor is $ Delta V_C = Q / C $ where $C$ is the capacitance.

/ Inductance: The voltage drop across an inductor is $ Delta V_L = -L dd(I) / dd(t) $ where $L$ is the inductance.

== Reading Resistors
There will be maximum 5 color bands on a resistor.
From the left to the right:
- 1-3: The first three digits of the resistance value.
- 4: The number of zeros following the first three digits (multiplier).
- 5: The tolerance of the resistance value.

Sometimes, there will be 4 bands only, where there are only 2 digits represented, followed by the number of zeros.

#let res-digit-colors = (
  "0": black,
  "1": orange.darken(50%), // brown
  "2": red,
  "3": orange,
  "4": yellow,
  "5": green,
  "6": blue,
  "7": purple,
  "8": color.gray,
  "9": white,
)

#let res-tolerance-colors = (
  "5": yellow.transparentize(50%), // gold
  "10": silver,
)

#figure(
  caption: [Resistor digit colors],
  grid(
    columns: res-digit-colors.len(),
    stroke: 0.5pt,
    inset: 0.8em,
    ..for (d, c) in res-digit-colors {
      (grid.cell(fill: c, text(font: "Fira Mono", stroke: 0.8pt + yellow, size: 2em, d)),)
    }
  ),
)

#figure(
  caption: [Resistor tolerance colors],
  grid(
    columns: res-tolerance-colors.len(),
    stroke: 0.5pt,
    inset: 0.8em,
    ..for (d, c) in res-tolerance-colors {
      (grid.cell(fill: c, text(font: "Fira Mono", stroke: 0.8pt + yellow, size: 2em, d + "%")),)
    }
  ),
)

== Kirchhoff's Laws
When traveling in the direction of the current, the voltage change through a resistor is negative, $Delta V = -I R$, and positive through a battery, $Delta V = +epsilon$.
When traveling against the direction of the current, invert the signs.

/ Kirchhoff's Current Law (KCL): The sum of currents entering a node is equal to the sum of currents leaving the node.
  $ Sigma I_"in" = Sigma I_"out" $

/ Kirchhoff's Voltage Law (KVL): The sum of voltage drops in a closed loop is equal to the sum of voltage rises.
  $ Sigma V_"drop" = Sigma V_"rise" $
  A 'closed loop' is a path that starts and ends at the same point, no matter the direction of current.

These two laws are crucial in analyzing circuits (solving problems), especially when appliances are not clearly connected in series or parallel.

