#import "../lib.typ": *
#show: setup.with(
  title: [MATH 256 _Differential Equations_],
  author: "Yecheng Liang",
)

#set math.vec(delim: "[")
#set math.mat(delim: "[")

#let ll = math.op[L]

= Differential Equations
#definition(title: [Differential Equation])[
  An equation that defines a function by giving a relationship between the function and its derivative.
]

#example[
  $
    y' + y = x.
  $
]

Integration is solving a trivial differential equation.

Given a first-order, linear differential equation, $dv(y, x) = a y$, a reasonable guess is $y = A e^(a x)$.
We can take any constant $A$ because the equation is linear.

== Separable Equations Method
For nonlinear differential equations, we would manipulate the equation so one side is expressed by $y$, the other by $x$ and $dd(x)$.
Then, integrating both sides gives us a relationship between $x$ and $y$.

#example[
  $
              dv(y, x) & = a y \
             dd(y) / y & = a dd(x) \
    integral dd(y) / y & = a integral dd(x) + C \
             ln abs(y) & = a x + C \
                     y & = e^(ln(abs(y))) \
                       & = e^(a x + C) \
                       & = e^c e^(a x) \
                       & = A e^(a x).
  $
]

== Integrating Factor Method
With a linear first-order equation, we can forcibly express it by only $x$.

Let $ll$ be an operator such that
$
  ll y & = (dv(, x) + p(x)) y \
       & = dv(y, x) + p(x) y \
       & = g(x).
$
So long as $p(x), g(x)$ are continuous, a solution exists.
And, if $ll y = 0$, we say the equation is homogeneous.

Let $F(x)$ be the _integrating factor_ such that
$
  F(x) dv(y, x) + F(x) p(x) y & = dv(, x) [F(x) y].
$
From the equation above we can see that, if we differentiate $F(x)$, we get itself multiplied by $p(x)$, looks much like our guess of exponential before.
Hence,
$
  F(x) & = e^(integral p(x) dd(x)).
$

Multiply $ll y$ by $F(x)$,
$
  e^(integral p(x) dd(x)) dv(y, x) + e^(integral p(x) dd(x)) p(x) y & = e^(integral p(x) dd(x)) g(x)
$
Notice that the LHS is differential of a product.
$
  dv(, x) [e^(integral p(x) dd(x)) y] & = e^(integral p(x) dd(x)) g(x) \
            e^(integral p(x) dd(x)) y & = integral e^(integral p(x) dd(x)) g(x) dd(x) + C \
                                    y & = e^(-integral p(x) dd(x)) (integral e^(integral p(x) dd(x)) g(x) dd(x) + C).
$

#problem[
  Solve
  $
    cases(
      ll y = y' + y = x,
      y(0) = 1
    )
  $

  #solution[
    Using the integral factor form, let
    $
       p(x) & = 1 \
       y(x) & = x \
      y'(x) & = 1.
    $
    Thus, we find the integrating factor to be
    $
      F(x) & = e^(integral p(x) dd(x)) \
           & = e^x.
    $
    Then, transform the equation by multiplying $F(x) = e^x$ to both sides.
    $
      e^x y' + e^x y & = [e^x y]' \
                     & = x e^x.
    $
    Notice that the LHS is differential of a product, undo the chain rule, we get
    $
      e^x y & = e^x x - e^x + C.
    $
    Don't forget the $C$ generated by the integrating both sides.

    Move the factor of integration to the RHS,
    $
      y & = x - 1 + C e^(-x)
    $
    Plug in $y(0) = 1$,
    $
      y(x) = x - 1 + 2e^(-x).
    $
  ]
]

#problem[
  Solve
  $
    ll y & = y' + y = sin(x).
  $

  #solution[
    Recall Euler's Equation,
    $
      e^(i x) = cos(x) + i sin(x).
    $

    Similar to the previous problem,
    $
          F(x) & = e^x ll y \
               & = [e^x y]' \
               & = e^x sin(x) \
      [e^x y]' & = Im e^((1 + i)x).
    $
    Integrate both sides,
    $
      e^x y & = Im e^((1 + i)x) / (1 + i) + C.
    $
    Turn the fraction term of RHS into proper form,
    $
      e^((1 + i)x) / (1 + i) & = (e^((1 + i)x) (1 - i)) / ((1 + i) (1 - i)) \
                             & = (e^((1 + i)x) (1 - i)) / 2.
    $
    Continue with the factor of integration method,
    $
      y & = Im (e^((1 + i)x) (1 - i) e^(-x)) / 2 + C e^(-x) \
        & = Im (e^(i x) (1 - i)) / 2 + C e^(-x) \
        & = Im ((cos(x) + i sin(x)) (1 - i)) / 2 + C e^(-x) \
        & = Im ((cos(x) - i^2 sin(x)) + (i sin(x) - i cos(x))) / 2 + C e^(-x) \
        & = Im ((cos(x) + sin(x)) + i (sin(x) - cos(x))) / 2 + C e^(-x) \
        & = (sin(x) - cos(x)) / 2 + C e^(-x).
    $
    No particular solution.
  ]
]

== Undetermined Coefficient Method
For a homogeneous linear equation, we can guess a particular solution, $y_p$.
- If $g(x) = x^n$, then $y_p = a_n x^n + a_(n-1) x^(n-1) + ... + a_1 x + a_0$.
- If $g(x) = e^(a x)$, then $y_p = A e^(a x)$.
- If $g(x) = sin(x) "or" cos(x)$, then $y_p = A cos(x) + B sin(x)$.
The guesses are linear combinations of all possible derivatives of $g(x)$.

The particular solution still carries undetermined coefficients.
Assume this $y_p$ to transform $ll y$.

= Higher Order ODEs

== Linear Second-order ODEs
Redefine the operator $ll$:
$
  ll y & := y'' + p(x) y' + q(x) y = g(x).
$
If $g(x) = 0$, we say the equation is homogeneous.

Such equations are common in superposition of waves and such.

== Constant Coefficient Equations
If $g(x) = 0$ and the coefficients are constant, like
$
  ll y = a y'' + b y' + c y = 0,
$
then,
$
     y & = e^(r x) \
  ll y & = (a r^2 + b r + c) e^(r x) = 0.
$

Since $e^(r x) eq.not 0$, solving the equation is the same as solving the contained quadratic equation.
If $Delta < 0$, then the roots are complex,
$
  r_(1, 2) & = lambda plus.minus i mu \
      y(x) & = e^(r x) (A cos(mu x) + B sin(mu x))
$

#problem[
  A stone thrown vertically up at speed $v_0$ at height $h$.
  Express its displacement as a function of $t$.

  #solution[
    $
                     y'' & = -g \
      integral y'' dd(t) & = integral -g dd(t) \
                      y' & = -g t + C \
                   y'(0) & = v_0 = C \
       integral y' dd(t) & = integral -g t + v_0 dd(t) \
                       y & = v_0 t - 1/2 g t^2 + D \
                    y(0) & = h = D \
                    y(t) & = h + v_0 t - 1/2 g t^2.
    $
  ]
]

== Initial Value Problem
With similar setup to the previous problem, but the coefficients may not be constants.

Given $ll y = 0$ and initial conditions $y(x_0) = y_0, y'(x_0) = v_0$, let $y_1(x), y_2(x)$ be two solutions to $ll y = 0$.
Since $ll$ is a linear operation, its solution is also linear.
$
     y(x) & = C_1 y_1(x) + C_2 y_2(x) \
   y(x_0) & = C_1 y_1(x_0) + C_2 y_2(x_0) \
          & = y_0 \
  y'(x_0) & = C_1 y'_1(x_0) + C_2 y'_2(x_0) \
          & = v_0.
$
This can be written as
$
  underbrace(mat(y_1(x_0), y_2(x_0); y'_1(x_0), y'_2(x_0)), A) mat(C_1; C_2) = mat(y_0; v_0).
$

For it to be solved as having constant coefficients, $det(A) eq.not 0$, i.e. $A^(-1)$ must exist.

#definition(title: [Wronsian Function])[
  Given $y_1(x), y_2(x)$,
  $
    W(y_1, y_2)(x) := mdet(y_1(x), y_2(x); y'_1(x), y'_2(x)).
  $
]

#definition(title: [Fundamental Set of Solutions])[
  Given $ll y = y'' + p(x) y' + q(x) y = 0$, the pair ${y_1(x), y_2(x)}$ is a set of fundamental solutions on an interval $I$, provided that $W(Y_1, y_2)(x_0)$ where $x_0 in I$.
]

So, an initial value problem has solution if $W(y_1, y_2)(x_0) eq.not 0$.

== Linear Dependency of Functions
Given two functions $f(x), g(x)$ which are valid on interval $I$, they are linearly dependent on $I$ if there exists non-zero $c_1, c_2$ such that
$
  c_1 y(x) + c_2 g(x) = 0.
$

If $y(x) = C_1 y_1(x) + C_2 y_2(x)$, then ${y_1, y_2}$ is a set of fundamental solutions.

== Simple Harmonic Motion
Second-order differential equations are common in problems where contributing factors also produce hindrances, like spring-mass and inductor-capacitor systems.

#example[
  Given a spring hanging a mass,
  $
    m dot.double(x) & = - m g - k x - beta dot(x) \
    m dot.double(x) + underbrace(beta dot(x), #[damping]) + underbrace(k x, #[energy\ storage]) & = underbrace(- m g, #[forcing]).
  $
]

When $beta = 0$, it is without damping, thus simple harmonic motion.

=== Free Undamped Oscillation
Ignore external influence ("free") and damping.

#example[
  $
                              g & = 0 \
                           beta & = 0 \
          m dot.double(x) + k x & = 0 \
                              x & = e^(r t) \
                        omega_0 & = sqrt(k/m) \
    dot.double(x) + omega_0^2 x & = 0 \
      (r^2 + omega_0^2) e^(r t) & = 0 \
                              r & = plus.minus i omega_0 \
                           y(t) & = A cos(omega_0 t) + B sin(omega_0 t) \
                                & = R cos(omega_0 t - phi) quad ("double angle") \
                                & = R cos(omega_0 t) cos(phi) + R sin(omega_0 t) sin(phi) \
                              A & = R cos(phi) \
                              B & = R sin(phi) \
                              R & = sqrt(A^2 + B^2) \
                          B / A & = tan(phi) \
                            phi & = tan^(-1)(B / A)
  $
]

=== Free Damped Oscillation
There is still no external forcing.

#example[
  $
                                      g & = 0 \
                                   beta & > 0 \
    m dot.double(x) + beta dot(x) + k x & = 0.
  $

  See this as a constant coefficient equation,
  $
                  x(t) & = e^(r t) \
    m r^2 + beta r + k & = 0 \
                 Delta & = beta^2 + 4 m k \
                     r & = (-beta plus.minus sqrt(Delta)) / (2m).
  $

  If $Delta < 0$, then
  $
    r_(1, 2) & = - beta / (2m) plus.minus i sqrt(4 m k - beta^2) / (2m) \
             & = - beta / (2m) plus.minus omega_1
  $
  where
  $
    omega_1 & = sqrt((4 m k - beta^2) / (4m^2)) \
            & = sqrt(k/m - beta^2 / (4m^2)) \
            & = sqrt(k/m (1 - beta^2 / (4 m k))) \
            & = sqrt(k/m) sqrt(1 - beta^2 / (4 m k)) \
            & = omega_0 sqrt(1 - beta^2 / (4 m k)).
  $

  Substitute it back, plus Euler's equation,
  $
    x(t) = e^(- beta / (2m) t) [A cos(omega_1) t + B sin(omega_1) t]
  $
  which is an underdamp.

  If $Delta > 0$, then solve for $r_1, r_2$ as usual.
  Since $beta, m, k > 0$, the roots will be negative,
  $
    x(t) = A e^(r_1 t) + B e^(r_2 t)
  $
  which is an overdamp.

  If $Delta = 0$, then
  $
    beta^2 - 4 m k & = 0 \
              beta & = 2 sqrt(m k) \
                 r & = - beta / (2 m k) \
              x(t) & = e^(- beta / (2m)) [A + B t]
  $
  which is a critcal damp.
]

== Inhomogeneous Second-order Equations
Define
$
  ll y & = y'' + p(x) y' + q(x) y = g(x)
$
where $g(x) eq.not 0$.

It has the general solution of
$
  y(x) & = y_P (x) + y_H (x)
$
where $ll y_P (x) = g(x), ll y_H (x) = 0$.

If $g(x) = 0$, then $y_P$ disappears, then we can solve the constant coefficient cases as usual.
$
              y_H & = e^(r x) \
  a r^2 + b r + c & = 0 \
                r & = ... \
             y(x) & = y_H (x) = c_1 y_1 (x) + c_2 y_2 (x).
$

To find $y_P$, we guess it to be a linear combination of all possible derivatives of $g(x)$.
- $x^n$: $y_P = a_n x^n + a_(n-1) x^(n-1) + ... + a_1 x + a_0$.
- $e^(a x)$: $y_P = A e^(a x)$.
- $sin(omega x), cos(omega x)$: $y_P = A cos(omega x) + B sin(omega x)$.

#note-box[
  This does not work when one or more terms of $y_P$ is a solution to the homogeneous equation.
  To make it work, we multiply the guess of $y_P$ by one or more $x$, until the highest power of $ll y_P$ matches the ones in $g(x)$.
]

#problem[
  Solve $ll y = y'' + 3y' + 2y = e^x$.

  #solution[
    Guess $y_P = A e^x$.
    Solve for $y_H$ (omitted).
    $
       ll y_P & = A e^x + 3 A e^x + 2 A e^x = e^x \
      6 A e^x & = e^x \
            A & = 1/6.
    $
    Combine $y_P, y_H$,
    $
      y(x) & = 1/6 e^x + c_1 e^(-x) + c_2 e^(-2 x).
    $
  ]
]

== Forced Oscillations and Resonnance
For all periodic motions, we can write them into some
$
  m x'' + c x' + k x = F_0 cos(omega t).
$

=== Undamped Forced Motion and Resonnance
Since it is undamped, $c = 0$.

Recall that our spring-mass system has the homogeneous solution of
$
  x_H = C_1 cos(omega_0 t) + C_2 sin(omega_0 t)
$
where $omega_0 = sqrt(k/m)$ is the _natural frequency_.

If $omega eq.not omega_0$, we know $x_p = A cos(omega t)$ where $A$ is some constant.
Solve for $x_p$,
$
  x_P = F_0 / (m (omega_0^2 - omega^2)) cos(omega t).
$

The general solution is thus the linear combination of $x_h$ and $x_p$:
$
  x = C_1 cos(omega_0 t) + C_2 sin(omega_0 t) + F_0 / (m (omega_0^2 - omega^2)) cos(omega t).
$

=== Damped Forced Motion and Partial Resonnance
Let
$
        p & = c / (2m) \
  omega_0 & = sqrt(k/m).
$
Then,
$
  ll x_P = & dot.double(x_P) + beta / m dot(x_P) + k / m x_P = F_0 / m cos(omega t) \
         = & -omega^2 [A cos(omega t) + B sin(omega t)] \
           & + k / m [-A omega sin(omega t) + B omega cos(omega t)] \
           & + [A cos(omega t) + B sin(omega t)] \
         = & (omega_0^2 - omega^2) [A cos(omega t) + B sin(omega t)] \
           & + beta / m [-A omega sin(omega t) + B omega cos(omega t)] \
         = & cos(omega t) [A (omega_0^2 - omega^2) + B (omega beta) / m] \
           & + sin(omega t) [B (omega_0^2 - omega^2) - A (omega beta) / m].
$

Equate the first and last line, we know that the $sin... = 0, cos... = F_0 / m$.
So solve for $A, B$ (omitted).

Let $R = sqrt(A^2 + B^2)$, we can combine the $sin$ and $cos$ terms
$
  x_P (t) = & R cos(omega t - phi)
$
where $phi = tan^-1 (((omega beta) / m) / (omega_0^2 - omega^2))$.

== Cauchy-Euler Equation
Define
$
  ll y = & a x^2 y'' + b x y' + c y = 0
$
where $a, b, c$ are constants.

If $a = 0$, the equation becomes first-order and seperable.
$
  ln abs(y) = & - c / b ln abs(x) + D \
       y(x) = & e^(ln abs(y)) \
            = & e^(ln abs(x))^(-c/b) e^D \
            = & A x^(-c/b).
$

For the second-order equation, we guess that
$
        y = & x^r \
       y' = & r x^(r - 1) \
      y'' = & r (r - 1) x^(r - 2) \
     x y' = & r x^r \
  x^2 y'' = & r (r - 1) x^r.
$

Apply $ll$ on this guess: for all $x$,
$
               ll x^r = & [a r (r - 1) + b r + c] x^r \
                        & = 0 \
  a r^2 + (b - a) r + c & = 0.
$

Then solve it in similar fasion to the previous second-order equations.
- If $Delta > 0$,
  $
    y(x) = & C_1 x^(r_1) + C_2 x^(r_2).
  $
- If $Delta < 0$,
  $
    r_(1, 2) = & - (b - a) / (2 a) plus.minus ((-1) (4 a c - (b - a)^2)) \
             = & alpha plus.minus i beta
  $
  where $alpha, beta$ are obvious.
  $
    y(x) = & C_1 x^(alpha + i beta) + C_2 x^(alpha - i beta) \
         = & x^alpha [C_1 e^(i beta ln(x)) + C_2 e^(-i beta ln(x))] \
         = & x^alpha [A cos(beta ln(x)) + B sin(beta ln(x))].
  $
- If $Delta = 0$, the one repeated root $r = - (b - a) / (2 a)$.
  One solution is
  $
    y_1 (x) = x^r.
  $
  The other can be found via
  $
    y_2 (x) = & evaluated(pdv(, r) x^r)_(r = r_1) \
            = & evaluated(pdv(, r) e^(r ln(x)))_(r = r_1) \
            = & x^r ln(x).
  $
  This method is explained in the next section.
  $y(x)$ is then a linear combination of the two solutions.

// TODO
// $
//   oL x^r = & [a x^2 dv(, x, 2) + b x dv(, x) + c] x^r \
//          = & [a r^2 + (b - a) r + c] x^2 \
//          = & a [(r + (b - a) / (2a))^2 - overbrace((b - a)^2 - 4 a c, Delta = 0) / (4 a^2)] x^2 \
//          = & a (r + (b - a) / (2a))^2 x^r
// $
//
// $
//   oL(evaluated(pdv(x^r, r))_(r = 1)) = & 0.
// $

== Reduction of Order Method
Given the second-order differential equation.
If $y_1 (x)$ is a solution to the homogeneous equation, then the other solution $y_2 (x)$ can be found in form of
$
    y_2 (x) = & u(x) y_1 (x) \
   y'_2 (x) = & u(x) y'_1 (x) + u' (x) + y_1 (x) \
  y''_2 (x) = & u(x) y''_1 (x) + 2 u' (x) y'_1 (x) + u'' (x) + y_1 (x).
$
Since we know $ll y_1 = 0$, we can strip it from the expression of $ll y_2$:
$
  ll y_2 = & y''_2 + p(x) y'_2 + q(x) y_2 = g(x) \
         = & underbrace(u [y''_1 + p(x) y'_1 + q(x) y_1], ll y_1 = 0) + [u'' y_1 + (2 u' y_1 + p y_1 u')] \
         = & u'' y_1 + (2 u' y_1 + p y_1 u').
$
Let $W = u', W'' = u''$,
$
  W' + ((2 y'_1) / y_1 + p(x)) W = & g(x) / (y_1 (x)).
$
Go back to using the integrating factor method,
$
                 F(x) = & e^(2 integral y'_1 / y_1 dd(x) + integral p(x) dd(x)) \
                      = & e^(ln(y_1^2) + integral p(x) dd(x)) \
                      = & y_1^2 e^(integral p(x) dd(x)) \
  dv(, x) [F(x) W(x)] = & (F(x) g(x)) / (y_1 (x)) \
            F(x) W(x) = & integral (F(x) g(x)) / (y_1 (x)) dd(x) + C_2 \
        W(x) = u' (x) = & 1 / F(x) integral (F(x) g(x)) / (y_1 (x)) dd(x) + C_2 / F(x) \
                 u(x) = & C_2 integral 1 / F(x) dd(x) \
                        & + limits(integral)^x 1 / F(s) [limits(integral)^s (F(t) g(t)) / (y_1 (t)) dd(t)] dd(s) \
                 y(x) = & C_1 y_1 (x) + u(x) y_1 (x).
$

#problem[
  Solve
  $
    ll y = & x^2 y'' + x y' - 9 y = 0.
  $

  #solution[
    Let $y = x^r$.
    $
                   ll x^r = & [a r (r - 1) + b r + c] x^r \
                            & = 0 \
      a r^2 + (b - a) r + c & = 0
    $
    where $a = 1, b = 1, c = -9$.
    $
         Delta = & (b - a)^2 - 4 a c \
               = & 36 > 0; \
      r_(1, 2) = & (plus.minus sqrt(Delta)) / 2 \
               = & plus.minus 3 \
          y(x) = & C_1 x^3 + C_2 x^(-3).
    $
  ]
]

#problem[
  Solve
  $
    ll y = & x^2 y'' + x y' + 9 y = 0.
  $

  #solution[
    Similar to the previous problem,
    $
      r_(1, 2) = & plus.minus 3 i \
          y(x) = & C_1 cos(3 ln(x)) + C_2 sin(3 ln(x)).
    $
  ]
]

#problem[
  Solve
  $
    ll y = & x^2 y'' - x y' + y = 0.
  $

  #solution[
    $Delta = 0, r = 1$.
    $
      y(x) = & C_1 x' + C_2 x' ln(x).
    $
  ]
]

= Laplace Transform
This is a transformation useful in _linear systems _only (for now).
The reasons are that it
+ works for discountinuous and impulsive forcing;
+ easier than undetermined coefficient method;

It looks like
$
               ll y = & g(t) \
          "something" & "transforms" \
  D(s) [Y(s) + I C] = & G(s) \
               Y(s) = & 1 / D(s) [G(s) - I C] \
          "something" & "transforms" \
               y(t) = & ...
$

#definition(title: [Laplace Transform])[
  Given a (at least piecewise) continuous function $f(t)$ defined on $[0, oo)$.
  The Laplace Transform is, $F(s)$, is then
  $
    F(s) = llt (f(t)) (s) = & integral_(0)^(oo) e^(-s t) f(t) dd(t)
  $
  where $s > 0 "and may be complex"$.

  It is a linear operation.
]

For transformation conclusions, a table of Laplace Transforms is given for this course.
Most importantly,
$
  llt (dv(, t, n) f(t)) = & s^n F(s) - f^(n - 1) (0) - s f^(n - 2) (0) - ... - s^(n - 1) f(0)
$
and
$
  llt (e^(i a t)) = & (s + i a) / (s^2 + a^2) \
   llt (sin(a t)) = & a / (s^2 + a^2) quad s > 0 \
   llt (cos(a t)) = & s / (s^2 + a^2) quad s > abs(a).
$
which can all be proven by induction.

== Forced Simple Harmonic Motion
#problem[
  Solve
  $
    dot.double(x) + omega_0^2 x = & F_0 / m cos(omega t) \
              x(0) = dot(x) (0) = & 0
  $
  where $omega eq.not omega_0 = sqrt(k / m)$.

  #solution[
    $
             llt (dot.double(x)) + omega_0^2 llt (x) = & F_0 / m llt (cos(omega t)) \
      s^2 X(s) - dot(x)(0) - s x(0) + omega_0^2 X(s) = & F_0 / m s / (s^2 + omega^2) \
                              (s^2 + omega_0^2) X(s) = & F_0 / m s / (s^2 + omega^2) \
                                                X(s) = & F_0 / m s / ((s^2 + omega^2) (s^2 + omega_0^2)).
    $
    Let
    $
      A / (s^2 + omega^2) + B / (s^2 + omega_0^2) = & 1 / ((s^2 + omega^2) (s^2 + omega_0^2)) \
          A (s^2 + omega^2) + B (s^2 + omega_0^2) = & 1.
    $
    Let $s = i omega$, $1 = B (omega_0^2 - omega^2)$, $B = 1 / (omega_0^2 - omega^0)$.
    Let $s = i omega_0$, $1 = A (-omega_0^2 + omega^2)$, $A = -1 / (omega_0^2 - omega^0)$.
    $
      X(s) = & F_0 / (m (omega_0^2 - omega^2)) [s / (s^2 + omega^2) - s / (s^2 + omega^2)].
    $

    Notice that some terms are result of Laplace Transforms, we linearly inverse them:
    $
      x(t) = & F_0 / (m (omega_0^2 - omega^2)) [cos(omega t) - cos(omega_0 t)].
    $
  ]
]

The linearity of Laplace Transform makes it applicable to compleicated differential equations.

#problem[
  Solve
  $
    y'' + 4y' + 5y = & t e^(-t) - 3e^(-t) + 4e^(-2t) \
      y(0) = y'(0) = & 0.
  $

  #solution[
    Apply Laplace Transform to boths sides:
    $
      [s^2 Y(s) - s y(0) - y(0)'] + 4 [s Y(s) - y(0)] + 5 Y(s) = & 1 / (s + 1)^2 - 3 / (s + 1) - 4 / (s + 2) \
      (s^2 + 4s + 5) Y(s) = & s^2 / ((s + 1)^2 + (s + 2)) \
      Y(s) = & s^2 / ((s^2 + 4s + 5) (s + 1)^2 + (s + 2)) \
      = & (A s + B) / (s^2 + 4s + 5) + C / (s + 1)^2 + E / (s + 1) + F / (s + 2).
    $

    How do we solve this gigantic partial fraction?
    We can certainly solve the system of five equations, but we will see the other method below.
    #align(right)[cont.]
  ]
]

== Partial Fraction Tricks
Given a fraction of $s$:
$
  Y(s) = & N(s) / D(s).
$

=== Contribution of an Unrepeated Factor
When there is a _unrepeated_ $(s - a)$ factor in the denominator, we can conclude that $D(a) = & 0$, hence
$
                       Y(s) = & A / (s - a) + "Rest" \
               (s - a) Y(s) = & ((s - a) N(s)) / (D(s) - D(a)) \
                            = & A + (s - a) "Rest" \
  lim_(s -> a) (s - a) Y(s) = & lim_(s -> a) (s - a) / (D(s) - D(a)) N(s) \
                            = & A \
             N(a) / (D'(a)) = & A.
$

=== Contribution of a Repeated Factor
When there is a _repeated_ $(s - a)$ factor of $m$ times in the denominator, we can factor each of it out:
$
  Y(s) = & A_m / (s - a)^m + A_(m - 1) / (s - a)^(m - 1) + A_(m - 2) / (s - a)^(m - 2) + ... + A_1 / (s - a) + "Rest".
$
Let $Q(s) = (s - a)^m Y(s)$.
$
          Q(s) = & A_m + A_(m - 1) (s - a) + A_(m - 2) (s - a)^2 + ... + A_1 (s - a)^(m - 1) + (s - a)^m "Rest" \
          Q(a) = & A_m \
         Q'(a) = & A_(m - 1) \
        Q''(a) = & 2 A_(m - 2) \
  Q^(m - 1)(a) = & (m - 1)! A_1.
$

=== Contribution of a Complex Conjugate Pair
When there is a complex conjugate pair, $(s - a) (s - conj(a))$ in the denominator, let $a = alpha + i beta, b = alpha - i beta$.
$
  (s - a) (s - conj(a)) = & s^2 - 2 alpha s + alpha^2 + beta^2 \
                        = & (s - alpha)^2 + beta^2.
$
The complex conjugate pair is likely a result of a quadratic expression, force it to zero to solve for $alpha, beta$.

#solution[
  #align(right)[cont.]
  $
    s^2 + 4s + 5 = & s^2 + 4s + 4 + 1 \
                 = & (s + 2)^2 + 1 \
            Y(s) = & (A s + B) / ((s + alpha)^2 + beta^2) + "Rest".
  $
  Let $R(s) = (s - a) (s - conj(a)) Y(s)$.
  $
        R(s) = & A s + B + ((s - a) (s - conj(a))) "Rest" \
        R(a) = & A a + B \
             = & A (alpha + i beta) + B \
             = & (A alpha + B) + A beta i \
    Re(R(a)) = & A alpha + B \
    Im(R(a)) = & A beta i.
  $
  // TODO
]

== Discontinuous and Impossible Loads
#definition(title: [Heaviside Step Function])[
  $u(t)$, or written $H(t)$, is a function of that
  $
    u(t - a) = & cases(
                   0 quad & t < a,
                   1 & t > a
                 )
  $
  where $a$ is a constant.
]

$
  llt (u(t - a)) = & integral_(0)^(oo) e^(-s t) u(t - a) dd(t) \
                 = & integral_(a)^(oo) e^(-s t) dd(t) \
                 = & e^(-a s) / s.
$
As expected (integration by parts), $llt (u'(t - a))$ gives one more $s$ and hence
$
  llt (u' (t - a)) = & e^(-a s).
$

Similarly, let $tau = t - a$,
$
  llt (u(t - a) f(t - a)) = & integral_(a)^(oo) e^(-s t) f(t - a) dd(t) \
                          = & integral_(0)^(oo) e^(-s (a + tau)) f(tau) dd(tau) \
                          = & e^(-a s) integral_(0)^(oo) e^(-s t) f(tau) dd(tau) \
                          = & e^(-a s) F(s).
$

#definition(title: [Dirac Delta Function])[
  Let
  $
    d_k (t) = & cases(
                  1 / (2k) quad & abs(t) < k,
                  0 & abs(k) > k
                ),
  $
  the Dirac Delta function is defined by
  $
    delta(t) = & lim_(k -> 0) d_k (t).
  $
]

This function, despite having no apparent "area under the curve", is integrated to be one.
$
  integral_(-oo)^oo delta(t) dd(t) = & lim_(k -> 0) integral_(-k)^(k) 1 / (2k) dd(t) = 1.
$
Given a continuous function $f(t)$,
$
  integral_(-oo)^(oo) delta(t - t_0) f(t) dd(t) = & lim_(k -> 0) integral_(-oo)^(oo) d_k (t - t_0) f(t) dd(t) \
                                                = & lim_(k -> 0) integral_(t_0 - k)^(t_0 + k) f(t) / (2k) dd(t) \
                                                = & lim_(k -> 0) f(t) integral_(t_0 - k)^(t_0 + k) dd(t) / (2k) \
                                                = & f(t_0).
$

== Convolution Theorem
#definition(title: [Laplace Convolution])[
  Let $f, g$ be functions defined on $[0, oo)$, then
  $
    (f convolve g)(t) := & integral_(0)^(t) f(tau) g(t - tau) dd(tau).
  $

  This operation is linear, hence
  $
               (f convolve g) (t) = & (g convolve f) (t) \
    h convolve (alpha f + beta g) = & alpha h convolve f + beta g convolve g.
  $
]

#theorem(title: [Convolution Theorem])[
  If $H(s) = F(s) G(s)$, then $h = f convolve g$, i.e. $llt (f convolve g) (s) = F(s) G(s)$.
]

#problem[
  Transform
  $
    g(t) = & cases(
               2t quad & 0 < t < 1,
               2 & 1 < t
             ).
  $

  #solution[
    Rewrite $g(t)$ so it is transformable.
    $
      g(t) = & 2t - 2t u(t - 1) + 2 u(t - 1) \
           = & 2t - 2 (t - 1) u(t - 1) - 2 u(t - 1) + 2 u(t - 1) \
           = & 2t - 2(t - 1) u(t - 1)
    $
    where $u$ is a Heaviside function.
    $
      llt(g(t))(s) = G(s) = & 2 / s^2 - 2 / s^2 e^(-s) \
                            & = 2 / s^2 (1 - e^(-s))
    $
  ]
]

#problem[
  $
    y'' + y = g(x) = & 2t - 2u(t - 1) (t - 1) \
          y(0) = 0 = & y'(0).
  $

  #solution[
    $
      llt (y'') + llt (y) = G(s) = & s^2 Y(s) - y'(0) - s y(0) + Y(s) \
                                 = & 2 / s^2 (1 - e^(-s)).
    $
    Notice that how this is equivalent to the convolution method.
    $
      (s^2 + 1) Y(s) = & G(s) \
                Y(s) = & 1 / (s^2 + 1) G(s) \
                     = & 2 / (s^2 (s^2 + 1)) (1 - e^(-s)).
    $

    #solution(title: [Partial Fraction Expansion])[
      $
        2 / (s^2 (s^2 + 1)) = & 1 / s^2 - 1 / (s^2 + 1) \
                       Y(s) = & 2 (1 / s^2 - 1 / (s^2 + 1)) - 2 e^(-s) (1 / s^2 - 1 / (s^2 + 1)) \
                       y(s) = & 2 (t - sin(t)) - 2 u(t - 1) ((t - 1) - sin(t - 1)).
      $
    ]

    #solution(title: [Convolution Theorem])[
      $
        y(t) = & integral_(0)^(t) g(t) sin(t - tau) dd(tau) \
        = & integral_(0)^(t) [2 tau - 2 (tau - 1) u(tau - 1)] sin(t - tau) dd(tau) \
        = & integral_(0)^(t) underbrace(2 tau sin(t - tau), I_1) - underbrace(2 (tau - 1) u(tau - 1) sin(t - tau), I_2) dd(tau) \
        I_1 = & 2 integral_(0)^(t) tau sin(t - tau) dd(tau) \
        = & 2 [evaluated(tau cos(t - tau))_0^t - integral_(0)^(t) cos(t - tau) dd(tau)] \
        = & 2 [(t - 0) + evaluated(sin(t - tau))_0^t] \
        = & 2 (t - sin(t)). \
        I_2 = & 2 integral_(0)^(t) (tau - 1) u(tau - 1) sin(t - tau) dd(tau) \
        = & ... \
        = & 2 [(t - 1) - sin(t - 1)].
      $
    ]
  ]

]

= System of Linear Equations
A first-order linear system looks like
$
  dv(vb(x), t) = & A(t) vb(x) (t) + vb(f) (t).
$

Any linear $n$th-order ODE can be rewritten as a first-order linear system.
For each derivation of $x$, make a new $x_i$, so that each $x_i$ is at most order one.

Given a linear system, if $vb(x_1) (t), vb(x_2) (t)$ are solutions to the homogeneous equation
$
  vb(x)' = & A vb(x),
$
then so $vb(x) (t) = alpha vb(x_1) (t) + beta vb(x_2) (t)$.

Note how this is similar to solution to a second-order differential equation being the linear combination of two solutions.

#problem[
  Find the general solution of
  $
    x' = & -3x - 2y \
    y' = & -2x - 6y.
  $

  #solution[
    Let
    $
       vb(x) = & vec(x, y) \
           A = & mat(-3, -2; -2, -6) \
      vb(x)' = & A vb(x).
    $

    Similar to how we guessed the solutions of first-order equations, guess
    $
                              vb(x) (t) = & e^(r t) vb(v) \
                             vb(x)' (t) = & e^(r t) r vb(v) = A e^(r t) vb(v) = A vb(x) \
      e^(r t) r vb(v) - A e^(r t) vb(v) = & vb(0) \
                        (r I - A) vb(v) = & vb(0).
    $
    Looks familiar? $r$ is an eigenvalue for a nontrivial solution.
    Recall from MATH 152 that we do
    $
      det(r I - A) = & 0 \
                   = & mdet(r + 3, 2; 2, r + 6) \
               r_1 = & -7 \
               r_2 = & -2.
    $
    Use $r_1 = -7$,
    $
      mat(-4, 2; 2, -1) vec(v_1, v_2) = & vec(0, 0) \
                                  v_1 = & 1 \
                                  v_2 = & 2.
    $
    Use $r_2 = -2$,
    $
      mat(1, 2; 2, 4) vec(v_1, v_2) = & vec(0, 9) \
                                v_1 = & -2 \
                                v_2 = & 1.
    $

    The general solution is
    $
      vb(x) (t) = & c_1 e^(-7 t) vec(1, 2) + c_2 e^(-2 t) vec(-2, 1) \
      = & underbrace(mat(e^(-7 t), -2 e^(-2, t); 2 e^(-7 t), e^(-2 t)), #[$phi(t)$ \ the Fundamental Matrix]) vec(c_1, c_2).
    $

    #problem[
      Given
      $
        vb(x) (0) = & vec(5, 4),
      $
      find the particular solution.

      #solution[
        $
          vb(x) (t) = & phi(t) vb(c) \
          vb(x) (0) = & phi(0) vb(c) \
                    = & mat(1, -2; 2, 1) vec(c_1, c_2) \
                    = & vec(5, 4) \
                c_1 = & 13 / 5 \
                c_2 = & - 6 / 5.
        $

        #note-box[
          $
                vb(c) = & phi(0)^(-1) vb(x) (0) \
            vb(x) (t) = & underbrace(phi(t) phi(0)^(-1), #[$psi(t)$ \ the Flow/Propagator Matrix]) vb(x) (0).
          $
        ]
      ]
    ]
  ]
]

This matrix method works the same with equations after Laplace Transform, as the matrices yield the same determinant and so.

- Given a pair of real roots, solve as usual.

  The polarity of $r_1, r_2$ dictates propagation of the initial values:
  - If $r_1 < r_2 < 0$, then the values shrink.
  - If $0 < r_1 < r_2$, then the values grow.
  - If $r_1 < 0 < r_2$, then the initial value is a saddle point.

- Given a pair of complex roots,
  $
    r_(1, 2) = & alpha plus.minus i beta
  $
  where $beta eq.not 0$.
  Solving this would give complex pairs of eigenvalue and eigenvector.
  Use $r_1 = alpha + i beta$,
  $
    mat((alpha + i beta) - alpha, -beta; beta, (alpha + i beta) - alpha) vec(v_1, v_2) & = vec(0, 0) \
    i beta v_1 - i beta v_2 = & 1 \
    v_2 = & i v_1 \
    vb(v)_1 = & underbrace(vec(1, 0), vb(v)_"re") + i underbrace(vec(0, 1), vb(v)_"im").
  $
  Plug in the values,
  $
    vb(x) (t) = & e^((alpha + i beta) t) [vb(v)_"re" + i vb(v)_"im"] \
    = & e^(alpha t) [cos(beta t) + i sin(beta t)] [vb(v)_"re" + i vb(v)_"im"] \
    ... & "seperate real and imaginary parts" \
    =& A vb(x)_1 (t) + B vb(x)_2 (t) \
    =& e^(alpha t) { A [cos(beta t) vb(v)_"re" - sin(beta t) vb(v)_"im"] - B [sin(beta t) vb(v)_"re" + cos(beta t) vb(v)_"im"] } \
    =& underbrace(e^(alpha t) mat(cos(beta t), sin(beta t); -sin(beta t), cos(beta t)), phi(t)) vec(A, B) \
    vb(x) (0) =& vec(A, B) = vec(x_0, y_0).
  $
  Looks very familiar to MATH 152 content.
  Get length of the vector,
  $
    sqrt(x^2 + y^2) = & e^(alpha t) sqrt(x_0^2 + y_0^2).
  $
  It is evident now, that $alpha$ controls length variation, $beta$ controls rotation speed.

- Given a repeated root, we still solve as usual.
  #example[
    Solve
    $
      dv(vb(x), t) = & mat(3, -4; 1, -1) vb(x).
    $

    #solution[
      Guess $vb(x) = e^(r t) vb(v)$.
      $
                           det(r I - A) = & 0 \
              mdet(r - 3, 4; -1, r + 1) = & (r - 1)^2 \
                                        = & 0 \
                             r_(1, 2) = 1 \
        mat(-2, 4; -1, 2) vec(v_1, v_2) = & vec(0, 0) \
                                    v_1 = & 2 v_2 \
                                vb(v)_1 = & vec(2, 1).
      $
      Thus,
      $
        vb(x)_1 = & e^t vec(2, 1).
      $

      Guess $vb(x)_2 (t) = e^(r t) [vb(w) + t vb(u)]$, such that $vb(w)$ solves $(r I - A) vb(w) = - vb(v)_1$, giving contribution in the opposite direction.
      $
        vb(x)'_2 (t) = & e^(r t) [r vb(w) + vb(u) + r t vb(u)].
      $
      Solve $vb(x)'_2 - A vb(x)_2 = & 0$:
      $
        [(r I - A) vb(w) + vb(u)] + t [(r I - A) vb(u)] = & vb(0).
      $
      Since the first term cannot cancel itself, and the equation should hold for all $t$,
      $
        (r I - A) vb(u) = & vb(0) \
           -w_1 + 2 w_2 = & -1 \
                      w_1 & = 1 \
                    w_2 = & 0 \
            vb(x)_2 (t) = & e^t [vec(1, 0) + t vec(2, 1)] \
              vb(x) (t) = & C_1 e^t vec(2, 1) + C_2 e^t vec(1 + 2t, t).
      $
    ]
  ]

== Laplace Transform Method
Since Laplace Transform is linear, we can apply it directly on matrices.

Knowing that
$
          llt (y') = & s Y(s) - y(0) \
                 A = & mat(a, b; c, d) \
  vb(x)' - A vb(x) = & 0 \
         vb(x) (0) = & vb(x)_0,
$
we get
$
  s vb(X) (s) - vb(x) (0) - A vb(X) (s) = & 0 \
                    (s I - A) vb(X) (0) = & vb(x)_0 \
                              vb(X) (s) = & (s I - A)^(-1) vb(x)_0.
$

#problem[
  Let
  $
            A = & mat(3, -4; 1, -1) \
    vb(x) (0) = & vec(x_0, y_0).
  $
  Solve $vb(x)' - A vb(x) = vb(x) (0)$.

  #solution[
    $
      det(s I - A) = & (s - 1)^2 \
         vb(X) (s) = & 1 / (s - 1)^2 mat(s + 1, -4; 1, s - 3) vec(x_0, y_0) \
                   = & vec(
                         x_0 / (s - 1)^2 + (2 x_0 - 4 y_0) / (s - 1)^2,
                         (x_0 - 2 y_0) / (s - 1)^2 + y_0 / (s - 1)
                       ) \
         vb(x) (t) = & e^t vec(
                         x_0 + 2 t x_0 - 4 t y_0,
                         (x_0 - 2 y_0) t + y_0
                       ) \
                   = & e^t mat(1 + 2 t, -4 t; t, 1 - 2t) vec(x_0, y_0).
    $
  ]
]

#problem[
  Given the special case of
  $
    A = & mat(alpha, -beta; beta, alpha).
  $

  #solution[
    $
      det(s I - A) = & (s - alpha)^2 + beta^2 \
         vb(X) (s) = & 1 / ((s - alpha)^2 + beta^2) mat(s - alpha, beta; -beta, s - alpha) vb(x)_0 \
         vb(x) (t) = & e^(alpha t) mat(cos(beta t), sin(beta t); -sin(beta t), cos(beta t)) vb(x)_0.
    $
  ]
]

== Inhomogeneous Linear System
Adding a forcing term $vb(f) (t)$ into the RHS.

We assume $vb(f) (t) = 0$ to solve the homogeneous system, then...

=== Undetermined Coefficient Method

#figure(
  caption: [Common Guesses for Linear Systems],
  table(
    columns: 2,
    table.header($vb(f) (t)$, [Guess for $vb(x)_P$]),
    $e^(a t) vb(b)$, [$e^(a t) vb(u)$ \ or $e^(a t) (vb(u) + t vb(w))$ like in repeated roots],
    $sin(beta t) vb(v), cos(beta t) vb(v)$, $vb(a) cos(beta t) + vb(b) sin(beta t)$,
    $t^2$, $vb(a) t^2 + vb(b) t + vb(c)$,
  ),
)

=== Variation of Parameters Method
Notice that
$
  phi' (t) = & A phi(t),
$
hence guess that
$
   vb(x)_P = & phi(t) vb(u) (t) \
  vb(x)'_P = & phi' (t) vb(u) (t) + phi(t) vb(u)' (t).
$

Substitute them back,
$
  vb(x)_P - A vb(x)_P = & (underbrace(phi' (t) vb(u) (t), A phi(t) vb(u) (t)) + phi(t) (t) vb(u)' (t)) - A phi(t) vb(u) (t) \
  = & vb(f) (t) \
  vb(u)' (t) = & phi(t)^(-1) vb(f) (t) \
  vb(u) (t) = & integral_(0)^(t) phi(tau)^(-1) dd(tau) + vb(c) \
  vb(x) (t) = & phi(t) integral_(0)^(t) phi(tau)^(-1) vb(f) (tau) dd(tau) + underbrace(phi(t) vb(c), vb(x)_H)
$

=== Laplace Transform Method
If given initial conditions,
$
     vb(x)' - A vb(x) = & vb(f) (x) \
            vb(x) (0) = & vb(x)_0 \
  (s I - A) vb(X) (s) = & vb(F) (s) + vb(x)_0 \
            vb(X) (s) = & (s I - A)^(-1) [vb(F) (s) + vb(x)_0] \
            vb(x) (t) = & integral_(0)^(t) psi(t - tau) vb(f) (tau) dd(tau) + psi(tau) vb(x)_0
$
where $llt (psi(t)) = P(s)$.

#problem[
  $
    vb(x)' = mat(-2, 1; 1, -2) vb(x) + vec(4 e^(-t), 0)
  $

  #solution[
    $
      det(r I - A) = & mdet(r + 2, -1; -1, r + 2) \
                   = & r^2 + 4r + 3 \
                   = & 0 \
               r_1 = & -3 \
               r_2 = & -1. \
           vb(v)_1 = & vec(1, 1) \
           vb(v)_2 = & vec(1, -1). \
           vb(x)_H = & mat(e^(-t) vec(1, 1), e^(-3t) vec(1, -1)) vec(c_1, c_2).
    $
    Since $e^(-t)$ is already a part of $vb(x)_H$, we guess that
    $
      vb(x)_P = & e^(-t) (vb(u) + t vb(w))
    $
    to capture all possible derivatives of the $e^(-t)$ term.

    And since that
    $
      vb(f) (t) = & e^(-t) vec(4, 0),
    $
    we let $vb(w) = vb(v)_1$ to match the forcing term once combined.
    Hence, we use $r = -1$.
    $
      (r I - A) vb(u) = & - alpha vb(w) + vb(b) \
                alpha = & 2 \
                vb(u) = & vec(1, -1) \
              vb(x)_P = & e^(-t) vec(1 + 2t, -1 + 2t) \
                vb(x) = & vb(x)_P + vb(x)_H.
    $
  ]

  #problem[
    Furthermore, $vb(x) (0) = vb(0)$.

    #solution[
      $
        vb(0) = & vec(1, -1) + mat(1, 1; 1, -1) vec(c_1, c_2) \
        vb(c) = & - 1 / 2 mat(-1, -1; -1, 1) vec(-1, 1) \
          c_1 = & 0 \
          c_2 = & -1.
      $

      Or, using the convolution theorem,
      $
        vb(x) (t) = & phi(t) integral_(0)^(t) phi(tau)^(-1) vb(f) (tau) dd(tau) + phi(t) vb(c) \
                  = & integral_(0)^(t) psi(t, tau) vb(f) (tau) dd(tau) + phi(t) vb(c).
      $
      where $psi(t, tau) = phi(t) phi(t)^(-1)$.
    ]

    #solution[
      Since initial values are given, we can use Laplace Transform:
      $
                    s vb(X) (s) - vb(x) (0) = & A vb(X) (s) + vec(4 / (s + 1), 0) \
                        (s I - A) vb(X) (s) = & vec(4 / (s + 1), 0) \
        mat(s + 2, -1; -1, s + 2) vb(X) (s) = & vec(4 / (s + 1), 0) \
                                  vb(X) (s) = & 1 / ((s + 1) (s + 3)) mat(s + 2, 1; 1; s + 2) vec(4 / (s + 1), 0) \
                                  vb(X) (s) = & vec(
                                                  1 / (s + 1) - 1 / (s + 3) + 2 / (s + 1)^2,
                                                  2 / (s + 1)^2 - 1 / (s + 1) + 1 / (s + 3)
                                                ) \
                                  vb(x) (s) = & e^(-t) vec(1 + 2t, -1 + 2t) + e(-3t) vec(-1, 1).
      $
    ]
  ]
]

#problem[
  Solve
  $
     vb(x)' = & mat(-2, 1; 1, -2) vb(x) (t) + vec(0, 9t) \
    vb(x)_H = & mat(e^(-t) vec(1, 1), e^(-3t) vec(1, -1)) vec(c_1, c_2).
  $

  #solution[
    Since $vb(f) (t)$ is linear first-order, guess that
    $
       vb(x)_P = & vb(a) t + vb(b) \
      vb(x)'_P = & vb(a).
    $

    Using the undetermined coefficient method, substitute:
    $
       vb(x)'_P - A vb(x)_P = & {vb(a) - A vb(b)}_0 t^0 {-A vb(a)}_1 t^1 \
                            = & t vec(0, 9) \
      because "term of" t^0 = & 0 \
                    therefore & cases(
                                  {}_0 = & 0,
                                  -A vb(b) = & -vb(a)
                                ) \
                      vb(a) = & 1 / 3 vec(9, 18) \
                      vb(b) = & vec(-4, -5) \
                    vb(x)_P = & vec(3t - 4, 6t - 5).
    $
  ]

  #problem[
    Furthermore, given $vb(x) (0) = vb(0)$.

    #solution[
      $
        vb(X) (s) = & 1 / ((s + 1) (s + 3)) mat(s + 2, 1; 1, s + 2) vec(0, 9 / s^2) \
                  = & 9 vec(
                        1 / (s^2 (s + 1) (s + 3)),
                        1 / (s^2 (s + 3)) - 2 / (s^2 (s + 1) (s + 3))
                      ) \
                  = & 9 vec(
                        (1 / 3) / s^2 - (- 4 / 9) / s + (1 / 2) / (s + 1) - (1 / 18) / (s + 3),
                        (1 / 3) / s^2 - (1 / 9) / s + (1 / 9) (s + 3)
                      ) \
        vb(x) (s) = & ...
      $
    ]
  ]
]

#theorem[
  If given
  $
         vb(x)' = & A vb(x) + vb(f) (t) \
    vb(x)_H (t) = & mat(cos(beta t), sin(beta t); -sin(beta t), cos(beta t)) vec(c_1, c_2),
  $
  then guess that
  $
    vb(x)_P = & (vb(a) + t vb(c)) cos(beta t) + (vb(b) t + vb(d)) sin(beta t).
  $
]

= Partial Differential Equation

#example(title: [The Conservation Law])[
  Given a car lane, let the density of cars at a point be $u(x, t)$ cars per unit length, and the flux of cars at a point be $q(x, t)$ cars per unit time.

  Then, the change in number of cars within $[x, x + Delta x]$ and $[t, t + Delta t]$ can be represented in terms of the density of cars, or the flux of cars:
  $
    u(x, t + Delta t) Delta x - u(x, t) Delta x = & q(x, t) Delta t - q(x + Delta x, t) Delta t \
    (u(x, t + Delta t) - u(x, t)) / (Delta t) = & - (q(x + Delta x, t) - q(x, t)) / (Delta x) \
    lim_(Delta t -> 0) (u(x, t + Delta t) - u(x, t)) / (Delta t) = & - lim_(Delta x -> 0) (q(x + Delta x, t) - q(x, t)) / (Delta x) \
    pdv(u, t) + pdv(q, t) =& 0.
  $

  We know that the flux is a multiple of density, $q = c u$.
  Hence,
  $
    pdv(u, t) + c pdv(u, x) = & 0.
  $

  Similar to the ODE $y' = alpha y$ for which we guess that $y = e^(r x)$, here we guess that
  $
                            u(x, t) = & e^(k x + sigma t) \
                          pdv(u, t) = & sigma e^(k x + sigma t) \
                          pdv(u, x) = & k e^(k x + sigma t) \
    (sigma + c k) e^(k x + sigma t) = & 0 \
                              sigma = & - c k \
                            u(x, t) = & e^(k (x - c t)).
  $
]

#theorem(title: [Traveling Wave Solution])[
  For any differentiable function $f(x)$,
  $
    u(x, t) = & f(x minus.plus c t)
  $
  is a solution to
  $
    pdv(u, t) plus.minus c pdv(u, x) = & 0,
  $
  because $x' = x - c t$ (Galilean Transformation).
]

#example(title: [Smart Driver])[
  Following the previous example, but the drivers will slow down in case of increasing car density.
  $
    q = & c u - D pdv(u, x),
  $
  which makes
  $
    pdv(u, t) + c pdv(u, x) = & D pdv(u, x, 2).
  $
]

#example(title: [Diffusion -- Random Walks])[
  Given a line of trees which grows over time, the number of fruit flies on a tree is then $u(x, t)$.

  The fruit flies travel in between the trees.
  They have $p$ chance to jump to the left or right, and $1 - 2p$ chance to stay.

  $
    u(x, t + Delta t) = & p u(x + Delta x, t) + p u(x - Delta x, t) + (1 - 2p) u(x, t) \
                      = & u(x, t) + p [u(x + Delta x, t) + u(x - Delta x, t) - 2 u(x, t)].
  $

  Using Taylor's Theorem,
  $
    u(x + Delta x, t) = & u(x, t) + Delta x pdv(u, x) (x, t) + (Delta x)^2 / 2 pdv(u, x, 2) (x, t) + ... \
    u(x - Delta x, t) = & ...
  $
  all the way to the forth derivative ($(Delta x)^4 / 24 ...$).
  $
    u(x + Delta x, t) + u(x - Delta x, t) - 2 u(x, t) = & (Delta x)^2 pdv(u, x, 2) + (Delta x)^4 / 12 pdv(u, x, 4).
  $

  Substitute this into our $u(x, t + Delta t)$ model:
  $
    (u(x, t + Delta t) - u(x, t)) / (Delta t) = & p ((Delta x)^2) / (Delta t) pdv(u, x, 2) + p ((Delta x)^2) / (Delta t) ((Delta x)^2) / 12 pdv(u^4, x^2)
  $
  where $p ((Delta x)^2) / (Delta t) = D$ is constant.
  Let $Delta t, Delta x -> 0$, the LHS becomes definition of a partial derivative:
  $
    pdv(u, t) = & D pdv(u, x, 2).
  $
]

$D$, the diffusion coefficient, is determined by the circumstance (e.g. material).

#example(title: [Speed of a Random Walker])[
  Given a random walker walking back and forth on a line, each step, taking $Delta t$, is $S_i = plus.minus Delta x$ with equal chance of choosing either sign.
  Let $X_N$ be the total displacement.
  $
                        X_N = & S_1 + S_2 + S_3 + ... + S_N \
                   EE (X_N) = & 0 \
                      X_N^2 = & S_1^2 + S_2^2 + S_3^2 + ... + S_N^2 + 2 S_1 S_2 + 2 S_2 S_3 + ... + 2 S_(N - 1) S_N \
                            = & N (Delta x)^2. \
                        t_N = & N Delta t \
                          N = & t_N / (Delta t) \
                      X_N^2 = & t_N (Delta x)^2 / (Delta t) \
                          D = & p (Delta x)^2 / (Delta t) quad "where" p = 1 / 2 \
    (Delta x)^2 / (Delta t) = & 2 D \
                      X_N^2 = & 2 D t_N \
                        X_N = & sqrt(2 D t_N).
  $
]

In cases where the propagation is on a 2D plane, the equation simply becomes
$
  pdv(u, t) = & D (pdv(u, x, 2) + pdv(u, y, 2))
$
which is Laplace's Equation.

We can even apply Laplace Transformation on these PDEs.
$
  cases(
    pdv(u, t) = pdv(u, x, 2) & T = alpha^2 X^2 & ("parabolic"),
    pdv(u, t, 2) = c^2 pdv(u, x, 2) & T^2 - c^2 X^2 = 1 quad & ("hyperbolic"),
    pdv(u, x, 2) + pdv(u, y, 2) = 0 quad & X^2 + Y^2 = 1 & ("ellipse")
  )
$

#example(title: [Heat Equation Solution])[
  Given that $pdv(u, t) = alpha^2 pdv(u, x, 2)$, guess that
  $
                             u(x, t) = & e^(i k x + sigma t) \
                           pdv(u, t) = & sigma e^(i k x + sigma t) \
                        pdv(u, x, 2) = & (i k)^2 e^(i k x + sigma t) \
                                     = & -k^2 e^(i k x + sigma t) \
    pdv(u, t) - alpha^2 pdv(u, x, 2) = & (sigma + alpha^2 k^2) e^(i k x + sigma t) \
                                     = & 0 \
                               sigma = & - alpha^2 k^2 \
                             u(x, t) = & e^(i k x) e^(- alpha^2 k^2 t). \
                           e^(i k x) = & cos(k, x) + i sin(k x),
  $
  hence $k$ determines the frequency.

  #note-box[
    Guessing $u(x, t) = e(k x + sigma t)$ will give a solution, as in the Conservation Law example.
    However, that solution blows up with infinity, which does not match reality situations.
  ]
]

#problem(title: [Initial Boundary Problems for Heat])[
  Heating a metal bar with length $L$ from the middle.
  $
    pdv(u, t) = & alpha^2 pdv(u, x, 2) &              0 < x < L \
      u(0, t) = & u(L, t) = 0 quad     & ("boundary condition") \
      u(x, 0) = & f(x)                 &  ("initial condition")
  $

  Give $u(x, t)$.

  #solution[
    We know that
    $
      u(x, t) = & e^(i k x) e^(- alpha^2 k^2 t) \
              = & X(s) T(t)
    $
    where $X(x), T(t)$ are some variable functions separated from the original equation.

    $
                     pdv(u, t) = & X(x) T'(t) \
                  pdv(u, x, 2) = & X''(x) T(t) \
                     pdv(u, t) = & alpha^2 pdv(u, x, 2) \
                    X(x) T'(t) = & alpha^2 X''(x) T(t) \
      (T'(t)) / (alpha^2 T(t)) = & (X''(x)) / X(x).
    $
    Since the two partial derivatives are likeliest independent, this equality in ratio suggests that they are a constant value, call it $-lambda$.
    $
      llt T = & -lambda alpha^2 integral dd(t) + c \
       T(t) = & A e^(-alpha^2 mu^2 t).
    $

    Given the boundary condition, we know that $X(0) = X(L) = 0$.
    Let $lambda = mu^2$.
    $
      X'' + mu^2 X = & 0 \
       dv(X, x, 2) = & - mu^2 X.
    $

    - If $mu = 0$, guess that
      $
                     X(x) = & A x + B \
        because X(0) = X(L) & = 0 \
          therefore A = B = & 0 quad ("trivial")
      $

    - If $mu > 0$, guess that
      $
                        X(x) = & e^(r x) \
        (r^2 + mu^2) e^(r x) = & 0 \
                           r = & plus.minus i mu \
                        X(x) = & A cos(mu x) + B sin(mu x).
      $

    Using $X(0) = 0$, we get $A = 0$.
    Then, use $X(L) = 0$,
    $
          B sin(mu L) = & 0 \
               mu_n L = & n pi \
      mu_n = (n pi) / L
    $
    where $n in NN$.

    $
      u_n (x, t) = & X_n (x) T_n (t) \
                 = & sin((n pi) / L x) e^(-alpha^2 ((n pi) / L)^2 t).
    $
    With superposition, the actual $u$ is the sum of all $u_i$.
    $
      u(x, t) = & sum_(n = 1)^oo B_n u_n (x, t).
    $
    Use the initial condition, $u(x, 0) = f(x)$, to find $B_n$.
    $
      f(x) = u(x, 0) = & sum_(n = 1)^oo B_n sin((n pi x) / L)
    $
    which is a Fourier Sine Series.

    Use integrating coefficient, let
    $
      f(x) = & sum_(n = 1)^oo B_n sin((n pi x) / L),
    $
    then
    $
      integral_(0)^(L) sin((m pi x) / L) f(x) dd(x)
      = & sum_(n = 1)^oo B_n underbrace(integral_(0)^(L) sin((m pi x) / L) sin((n pi x) / L) dd(x), I_(m n))
    $
    where $m$ is some constant.

    - If $m eq.not n$:
      Using the trigonometry identity of $cos(a plus.minus b) = cos(a) cos(b) minus.plus sin(a) sin(b)$,
      $
        1 / 2 [cos(A + B) - cos(A - B)] = & sin(A) sin(B).
      $
      Let $A = (m pi x) / L, B = (n pi x) / L$,
      $
        I_(m n) = & 1 / 2 integral_(0)^(L) [cos(((m + n) pi x) / L) - cos(((m - n) pi x) / L)] dd(x) \
                = & 1 / 2 [
                      evaluated(cos(((m + n) pi x) / L) / (((m + n) pi x) / L))_0^L
                      - evaluated(cos(((m - n) pi x) / L) / (((m - n) pi x) / L))_0^L
                    ]
      $

    - If $m = n$:
      $
        I_(m m) = & integral_(0)^(L) sin^2 ((m pi x) / L) dd(x).
      $
      Using the trigonometry identity of $cos(2a) = cos^2 (a) - sin^2 (a) = 1 - 2 sin^2 (a)$,
      $
        I_(m m) = & 1 / 2 integral_(0)^(L) [1 - cos^2 ((m pi x) / L)] dd(x) \
                = & L / 2.
      $

    Now, we can remove all $m eq.not n$ terms.
    $
      integral_(0)^(L) sin((m pi x) / L) f(x) dd(x) = & B_m I_(m m) \
                                                    = & B_m L / 2 \
                                                B_n = & 2 / L integral_(0)^(L) sin((m pi x) / L) f(x) dd(x).
    $
    This and $u(x, t)$ in terms of $B_n$ gives the final solution.
  ]
]

#problem[
  Given $f(x) = x$ for $x in [0, L = pi]$.
  Transform it into a Fourier Sine Series.

  #solution[
    $
       B_n = & 2 / pi integral_(0)^(pi) x sin(n x) dd(x) \
           = & 1 / 2 [
                 evaluated(-x cos(n x) / n)_0^pi + 1 / n integral_(0)^(pi) cos(n x) dd(x)
               ] \
           = & (-1)^(n + 1) dot 2 / n \
      f(x) = & sum_(n = 1)^oo B_n sin(n x).
    $
  ]
]

#problem(title: [Neumann Initial & Boundary Value Problem])[
  For $x in (0, L), t > 0$,
  $
                              pdv(u, t) = & alpha^2 pdv(u, x, 2) \
    pdv(u, x) (0, t) = pdv(u, x) (L, t) = & 0 \
                                u(x, 0) = & f(x).
  $
  Give $u(x, t)$.

  #solution[
    Let $u(x, t) = X(x) T(t)$.
    $
                     pdv(u, t) = & X(x) T'(t) \
                               = & alpha^2 pdv(u, x, 2) \
                               = & alpha^2 X''(x) T(t) \
      (T'(t)) / (alpha^2 T(t)) = & (X''(x)) / X(x) \
                               = & - lambda \
                               = & - mu^2.
    $

    Solve for $T(t)$, (make ODE, simple guess)
    $
      T(t) = & A e^(-alpha^2 mu^2 t).
    $

    Solve for $X(x)$.
    $
      X''(x) + mu^2 X(x) = & 0.
    $

    - If $mu = 0$,
      $
        X''(x) = & 0 \
         X'(x) = & A,
      $
      so we guess that
      $
           X(x) = & A x + B \
        X_0 (x) = & 1 quad ("we assume")
      $

    - If $mu > 0$, we guess that
      $
        X(x) = & e^(r x),
      $
      so
      $
           r^2 + mu^2 = & 0 \
                    r = & plus.minus mu i \
                 X(x) = & A cos(mu x) + B sin(mu x) \
                X'(x) = & -A mu sin(mu x) + B mu cos(mu x). \
        because X'(0) = & 0 \
          therefore B = & 0 \
                 X(x) = & A cos(mu x) \
                X'(x) = & -A mu sin(mu x).
      $
      Then use the $L$ boundary,
      $
        because -A mu sin(mu L) = & 0 \
                 therefore mu_n = & (n pi) / L
      $
      where $n = 1, 2, ...$.

    $
      lambda_n = mu_n^2 = & cases(
                              0 & n = 0,
                              ((n pi) / L)^2 quad & n in { 1, 2, ... }
                            ) \
                X_n (x) = & cases(
                              1 & n = 0,
                              cos((n pi x) / L) quad & n in { 1, 2, ... }
                            ) \
                u(x, t) = & A_0 + sum_(n = 1)^oo A_n e^(-alpha^2 ((n pi) / L)^2 t) cos((n pi x) / L) \
         f(x) = u(x, 0) = & A_0 + sum_(n = 1)^oo A_n cos((n pi x) / L). quad ("Fourier Cosine Series")
    $
  ]

  #theorem[
    For such a problem,
    $
      u(x, t) = & A_0 + sum_(n = 1)^oo A_n e^(-alpha^2 ((n pi) / L)^2 t) cos((n pi x) / L)
    $
    where
    $
              A_0 = & 1 / L integral_(0)^(L) f(x) dd(x) \
                  = & 1 / 2 underbrace([2 / L integral_(0)^(L) f(x) dd(x)], a_0) \
              A_n = & 2 / L integral_(0)^(L) f(x) cos((n pi x) / L) dd(x) \
             f(x) = & a_0 / 2 + sum_(n = 1)^oo a_n cos((n pi x) / L) \
      "where" a_n = & 2 / L integral_(0)^(L) f(x) cos((n pi x) / L) dd(x) quad n in NN.
    $

    $f(x)$ is known.
  ]
]

#problem(title: [Periodic Boundary Condition])[
  $
            pdv(u, t) = & alpha^2 pdv(u, x, 2) quad -L < x < L, t > 0 \
             u(-L, t) = & u(L, t) quad ("periodic") \
    pdv(u, x) (-L, t) = & pdv(u, x) (L, t) \
              u(x, 0) = & f(x)
  $

  #solution[
    Use the same transformation to arrive at
    $
                 T(t) = & A e^(-alpha^2 mu^2 t) \
                X(-L) = & X(L) \
               X'(-L) = & X'(L) \
      X''(x) + mu^2 X = & 0.
    $

    - If $mu = 0$,
      $
         X'' = & 0 \
          X' = & A \
           X = & A x + B \
           A = & 0 \
        mu_0 = & 0 \
         X_0 = & 1.
      $

    - If $mu > 0$,
      $
        X''(x) + mu^2 X = & 0 \
                   X(x) = & A cos(mu x) + B sin(mu x) \
                  X'(x) = & -A mu sin(mu x) + B mu cos(mu x) \
          2 B sin(mu L) = & 0 \
          2 A sin(mu L) = & 0 \
                   mu_L = & n pi quad n = 1, 2, ... \
                   mu_n = & (n pi) / L.
      $

    Hence, $X_n$ is of eigenfunction ${ cos((n pi x) / L), sin((n pi x) / L) }$.

    Use the previous $m, n$ abstraction, let
    $
      I_(m n) = & integral_(0)^(L) sin((m pi x) / L) sin((n pi x) / L) dd(x) \
      J_(m n) = & integral_(0)^(L) cos((m pi x) / L) cos((n pi x) / L) dd(x).
    $

    Integrating over a symmetrical interval calls for two conclusions for even and odd functions.
    $
      integral_(-L)^(L) f(x) dd(x) = & integral_(-L)^(0) f(x) dd(x) + integral_(0)^(L) f(x) dd(x) \
                                   = & integral_(L)^(0) f(-t) (-dd(t)) + integral_(0)^(L) f(t) dd(t) \
                                   = & integral_(0)^(L) [f(-t) + f(t)] dd(t) \
                                   = & cases(
                                         0 quad & f "is odd",
                                         2 integral_(0)^(L) f(t) dd(t) quad & f "is even"
                                       ).
    $

    Vectorize the coefficients of $f(x)$,
    $
      integral_(-L)^(L) f(x) vec(1, cos((m pi x) / L), sin((m pi x) / L)) dd(x) =& A_0 integral_(-L)^(L) vec(1, cancel(cos((m pi x) / L)), cancel(sin((m pi x) / L))) dd(x) \
      & + sum_(n = 1)^oo A_n integral_(-L)^(L) vec(cancel(1), cos((m pi x) / L), cancel(sin((m pi x) / L))) cos((n pi x) / L) dd(x) \
      & + sum_(n = 1)^oo B_n integral_(-L)^(L) vec(cancel(1), cancel(cos((m pi x) / L)), sin((m pi x) / L)) sin((n pi x) / L) dd(x) \
      = & A_0 vec(2L, 0, 0) + sum_(n = 1)^oo A_n vec(0, 2 J_(m n), 0) + sum_(n = 1)^oo B_n vec(0, 0, 2 I_(m n)).
    $

    Then, reduce the expression of each row...
  ]

  #theorem[
    For such a problem,
    $
      lambda_n = & ((n pi) L)^2 quad n in {0} union {1, 2, ...} \
          X_n in & {1} union { cos((n pi x) / L), sin((n pi x) / L) } \
       u(x, t) = & A_0 + e^(-alpha^2 ((n pi ) / x)^2 t) [A_n cos((n pi x) / L) + B_n sin((n pi x) / L)] \
          f(x) = & A_0 + sum_(n = 1)^oo [A_n cos((n pi x) / L) + B_n sin((n pi x) / L)]
    $
    where $A_0 = a_0 / 2, A_n = a_n, B_n = b_n$,
    $
      a_n = & 1 / L integral_(-L)^(L) f(x) cos((n pi x) / L) dd(x) quad n >= 0 \
      b_n = & 1 / L integral_(-L)^(L) f(x) sin((n pi x) / L) dd(x) quad n >= 1.
    $
    This is the _full-range_ Fourier Series.

    Using parity of $f$, we can reduce the full-range series to a half-range series.

    - If $f$ is odd,
      $
        a_n = & 0 \
        b_n = & 2 / L integral_(0)^(L) f(x) sin((n pi x) / L) dd(x).
      $
    - If $f$ is even,
      $
        a_n = & 2 / L integral_(0)^(L) f(x) cos((n pi x) / L) dd(x) \
        b_n = & 0.
      $

    #note-box[
      $L$ is only half the period.
    ]
  ]
]

#problem[
  Find the half-range Fourier Cosine Series of $f(x) = x$ with period $2pi$ on $[0, pi]$.

  #solution[
    $
                a_0 = & 2 / pi integral_(0)^(pi) x dd(x) \
                    = & 2 / pi evaluated(x^2 / 2)_0^pi \
                    = & pi \
                a_n = & 2 / pi integral_(0)^(pi) x cos(n x) dd(x) \
                    = & 2 / pi [((-1)^n - 1) / n^2] \
      f(x) = x approx & pi / 2 + 2 sum_(n = 0)^oo ((-1)^n - 1) / n^2 cos(n x).
    $
  ]

  For the Fourier Series outside of the period we solved for, there are three ways to expand to them.

  / Periodic Txtension: Copy-and-pasting the original period over.

  / Odd Extension: Expanding the series while making it odd, like a sine wave, from where it extensed.

  / Even Extension: Expanding the series while making it even, like a cosine wave, from where it extended.

  #problem[
    Periodically extend the series.

    #solution[
      $
         2L = & pi \
          L = & pi / 2 \
        a_0 = & 1 / (pi / 2) [integral_(-pi / 2)^(0) (x + pi) dd(x) + integral_(0)^(pi / 2) x dd(x)] \
            = & pi.
      $
      Notice that this is the same as the original series: periodic extension simply copies the wave.
      $
                  a_n = & 1 / (pi / 2) integral_(0)^(pi) x cos((n pi x) / (pi / 2)) dd(x) \
                      = & 2 / pi integral_(0)^(pi) x cos(2 n x) dd(x) \
                      = & 2 / pi [evaluated(x sin(2 n x) / (2 n))_0^pi - 1 / (2 n) integral_(0)^(pi) sin(2 n x) dd(x)] \
                      = & 0 \
                  b_n = & 2 / pi integral_(0)^(pi) x sin(2 n x) dd(x) \
                      = & - 1 / n \
        f(x) = x approx & pi / 2 - sum_(n = 1)^oo sin(2 n x) / n.
      $
    ]
  ]
]

#theorem(title: [Convergence Theorem])[
  Assume that $f, f'$ are piecewise continuous, and of period $2L$.
  Then,
  $
                  S_N (x) = & a_0 / 2 + sum_(n = 1)^N [a_n cos((n pi x) / L) + b_n sin((n pi x) / L)] \
    lim_(N -> oo) S_N (x) = & (f(x^+) + f(x^-)) / 2.
  $

  There might be a jump, $J = f(x^+) - f(x^-)$, at the pieces' joint.
  $
    g(x) = & f(x) - J u(x)
  $
  makes a continuous function.
]

#problem(title: [continued])[
  $
                      a_n = & 2 / pi [((-1)^n - 1) / n^2] \
                  S_N (x) = & 2 / pi sum_(n = 1)^N [((-1)^n - 1) / n sin(n x) ] \
                 S'_N (x) = & 2 / pi sin(2 (N + 1) x) / sin(x) \
    lim_(x -> 0) S'_N (x) = & lim_(x -> 0) [2 / pi cos(2 (N + 1) x) / cos(x) dot 2 (N + 1)] quad ("LHopital's")
  $
  which is to get $x_0$.
]

== Inhomogeneous PDE

#problem[
  $
    pdv(u, t) = & alpha^2 pdv(u, x, 2) quad 0 < x < L, t > 0 \
      u(0, t) = & a \
      u(L, t) = & b \
      u(x, 0) = & f(x).
  $
  The only difference is the boundary condition.

  #solution[
    Since physics tends to balance things out, we guess that the solution should be a straight line connecting $(0, a)$ and $(L, b)$.
    $
      u^oo (x) = & (b - a) / L x + a.
    $
    A straight line means a zero discriminant.
    $
      pdv(u^oo, t) = alpha^2 pdv(u^oo, x, 2) = & 0 \
                                 u^oo (x, t) = & u^oo (x).
    $

    Assume that
    $
      u(x, t) = & u^oo + v(x, t)
    $
    where $v$ is the particular solution.

    Plugin the initial and boundary conditions,
    $
        pdv(u, t) = & pdv(, t) [u^oo (x) + v(x, t)] \
                  = & alpha^2 (pdv(u^oo, x, 2) + pdv(v, x, 2)) \
                  = & alpha^2 pdv(u, x, 2) \
        pdv(v, t) = & pdv(v, x, 2) \
      a = u(0, t) = & u^oo (0) + v(0, t) \
                  = & a + v(0, t) \
          v(0, t) = & 0 \
      b = u(L, t) = & u^oo (L) + v(L, t) \
                  = & b + v(L, t) \
          v(L, t) = & 0 \
             f(x) = & u(x, 0) \
                  = & u^oo (x) + v(x, 0) \
          v(x, 0) = & f(x) = u^oo (x).
    $

    Notice that $v(x, t)$ actually has homogeneous boundary conditions, solve for it using Fourier Series,
    $
      v(x, t) = & sum_(n = 1)^oo b_n e^(-alpha^2 ((n pi) / L)^2 t) sin((n pi x) / L) \
          b_n = & 2 / L integral_(0)^(L) [f(x) - u^oo (x)] sin((n pi x) / L) dd(x) \
      u(x, t) = & (b - a) / L x + a + sum_(n = 1)^oo b_n e^(-alpha^2 ((n pi) / L)^2 t) sin((n pi x) / L).
    $
  ]
]

#problem[
  The previous setup, but
  $
    pdv(u, t) = & alpha^2 pdv(u, x, 2) + sigma(x),
  $

  #solution[
    We still guess with
    $
      pdv(u^oo, t) = & 0.
    $
    However, $sigma(x)$ makes our guess not a straight line.
    $
      alpha^2 pdv(u^oo, x, 2) + sigma(x) = & 0 \
                            pdv(u^oo, x) = & - 1 / alpha^2 integral_(0)^(x) sigma(s) dd(s) + A \
                            pdv(u^oo, x) = & - 1 / alpha^2 integral_(0)^(x) [integral_(0)^(L) sigma(s) dd(s)] dd(x) + A x + B \
                                         = & F(x) + A x + B.
    $

    Then, use the boundary conditions,
    $
        u^oo (0) = & a \
                 = & F(0) + B \
               B = & a - F(0) \
      u^oo (L) = b \
                 = & F(0) + A L + (a - F(0)) \
               A = & (b - a) / L - (F(L) - F(0)) / L.
    $

    Assume that
    $
      u(x, t) = & u^oo (x) + v(x, t).
    $
    ...we get
    $
              pdv(v, t) = & alpha^2 pdv(u, x, 2) \
      v(0, t) = v(L, t) = & 0 \
                v(x, 0) = & f(x) - u^oo (x) \
                      ... &
    $
  ]
]

#problem(title: [Neumann Boundary Condition])[
  The previous setup, but the function in boundary condition is $pdv(u, x)$ instead of $u$.

  #solution[
    Again, we reply on the fact that physics likes steady states.
    Find a steady solution, i.e. $pdv(u^oo, t) = 0$, in cases where $sigma(x) = 0$ or not.

    - If $sigma(x) = 0$,
      $
            pdv(u^oo, x) (0) = & a \
                    u^oo (b) = & b \
        pdv(u^oo, x) (0) = a = & pdv(u^oo, x) (L) = b.
      $

    - If $sigma(x) eq.not 0$,
      $
        pdv(u^oo, t) = 0 = & alpha^2 pdv(u^oo, x, 2) + sigma(x) \
        pdv(u^oo, x, 2) = & - 1 / alpha^2 sigma(x) \
        pdv(u^oo, x) = & - 1 / alpha^2 underbrace(integral_(0)^(x) sigma(s) dd(s), G(x)) + A \
        u^oo = & - 1 / alpha^2 integral_(0)^(x) G(x) dd(x) + A x + B \
        a = & pdv(u^oo, x) (0) \
        = & G(0) + A \
        A = & a - G(0) \
        b = & pdv(u^oo, x) (L) \
        = & G(L) + A \
        A = & b - G(L) \
        therefore a - G(0) = & b - G(L) \
        b - a + 1 / alpha^2 integral_(0)^(L) sigma(s) dd(s) = & 0.
      $
  ]
]

If we guess that
$
  u(x, t) = & e^(i k + sigma t)
$
for a physical solution, then the general solution would be
$
  u(x, t) = & F(x - c t) + G(x + c t).
$

Given a point $(x, t)$, the solution means that $(x, t)$ can only be influenced by $[x - c t, x + c t]$, which is like a triangle formed by lines from $(x, t)$ where $c$ is the inverse slope.

#problem(title: [d'Alembert's Wave Solution (Infinite String)])[
  Given an infinitely long string, there is no boundary condition.
  $
        pdv(u, t, 2) = & c^2 pdv(u, x, 2) quad -oo < x < oo, t > 0 \
             u(x, 0) = & f(x) \
    pdv(u, t) (x, 0) = & g(x).
  $

  #solution[
    $
                     u(x, t) = & F(x - c t) + G(x + c t) \
            pdv(u, t) (x, t) = & -c F'(x - c t) + c G'(x + c t) \
                     u(x, 0) = & F(x) + G(x) = f(x) quad                                                              & (1) \
            pdv(u, t) (x, 0) = & -c F'(x) + c G'(x) = g(x) quad                                                       & (2) \
            -c F(x) + c G(x) = & integral_(0)^(x) g(s) dd(s) + A quad                                                 & (3) \
      c (1) - (3) : 2 c F(x) = & c f(x) - integral_(0)^(x) g(s) dd(s) - A \
                        F(x) = & 1 / 2 f(x) - 1 / (2 c) integral_(0)^(x) g(s) dd(s) - A / (2 c) \
      c (1) + (3) : 2 c G(x) = & c f(x) + integral_(0)^(x) g(s) dd(s) + A \
                        G(x) = & 1 / 2 f(x) + 1 / (2 c) integral_(0)^(x) g(s) dd(s) + A / (2 c) \
                     u(x, t) = & 1 / 2 [f(x - c t) + f(x + c t)] + 1 / (2 c) integral_(x - c t)^(x + c t) g(s) dd(s).
    $
  ]
]

#problem(title: [Finite String])[
  Given a finite string, there is a boundary condition.
  $
         pdv(u, t, 2) = & c^2 pdv(u, x, 2) quad 0 < x < L, t > 0 \
    u(0, t) = u(L, t) = & 0 \
              u(x, 0) = & f(x) \
     pdv(u, t) (x, 0) = & g(x).
  $

  #solution[
    Use seperation of variables instead,
    $
                  u(x, t) = & X(x) T(t) \
             pdv(u, t, 2) = & X(x) T''(t) \
                          = & c^2 X''(x) T(t) \
      T''(t) / (c^2 T(t)) = & (X''(x)) / X(x) \
                          = & -lambda = -mu^2.
    $
    For $T$,
    $
        T''(t) + mu^2 c^2 T(t) = & 0 \
      (r^2 + mu^2 c^2) e^(r t) = & 0 quad                         & "let" u = e^(r t) \
                             r = & plus.minus i mu c \
                          T(t) = & A cos(mu c t) + B sin(mu c t).
    $
    For $X$,
    $
      X''(x) + mu X(x) = & 0 \
      X(0) = X(L) = & 0 \
      lambda_n = mu^2_n = & ((n pi) / L)^2 quad & n in {1, 2, ...} \
      X_n (x) = & sin((n pi x) / L) \
      = & sin(mu_n x) \
      u(x, t) = & sum_(n = 1)^oo T_n (t) X_n (x) \
      = & sum_(n = 1)^oo [A_n cos(mu_n c t) + B_n sin(mu_n c t)] sin(mu_n x) \
      pdv(u, t) = & sum_(n = 1)^oo [-A_n mu_n c sin(mu_n c t) + B_n mu_n c cos(mu_n c t)] sin(mu_n x) \
      f(x) = u(x, 0) = & sum_(n = 1)^oo A_n sin(mu_n x) \
      A_n = & 2 / L integral_(0)^(L) f(x) sin(mu x) dd(x) \
      = & f_n \
      g(x) = pdv(u, t) (x, 0) = & sum_(n = 1)^oo (B_n mu_n c) sin(mu_n x) \
      B_n mu_n c = & 2 / L integral_(0)^(L) g(x) sin(mu x) dd(x) \
      = & g_n \
      u(x, t) = & sum_(n = 1)^oo f_n sin(mu_n x) cos(mu_n c t) \
      & + sum_(n = 1)^oo g_n / (mu_n c) sin(mu_n x) sin(mu_n c t).
    $
    Recall the double angle formula:
    $
                         sin(alpha plus.minus beta) = & sin(alpha) cos(beta) plus.minus cos(alpha) sin(beta) \
      1 / 2 [sin(alpha - beta) + sin(alpha + beta)] = & sin(alpha) cos(beta) \
                         cos(alpha plus.minus beta) = & cos(alpha) cos(beta) minus.plus sin(alpha) sin(beta) \
      1 / 2 [cos(alpha - beta) - cos(alpha + beta)] = & sin(alpha) sin(beta).
    $
    Use them to expand $u(x, t)$:
    $
      u(x, t) = & 1 / 2 sum_(n = 1)^oo f_n [sin(mu_n (x - c t)) + sin(mu_n (x + c t))] \
                & + 1 / (2 c) sum_(n = 1)^oo [cos(mu_n (x - c t)) - cos(mu_n (x + c t))].
    $
    Looks like the d'Alembert's Wave Solution.

    Furthermore, we find the odd extension of $f, g$:
    $
                           f^"odd"_(2L) (x) = & sum_(n = 1)^oo f_n sin(mu_n (x)) \
                           g^"odd"_(2L) (x) = & sum_(n = 1)^oo g_n sin(mu_n (x)) \
      integral^x g^"odd"_(2L) (s) dd(s) + A = & -sum_(n = 1)^oo g_n / mu_n cos(mu_n x) \
                                    u(x, t) = & 1 / 2 [f^"odd"_(2L) (x - c t) + f^"odd"_(2L) (x + c t)] \
                                              & + 1 / (2 c) integral_(x - c t)^(x + c t) g^"odd"_(2L) (s) dd(s).
    $
    It is the same for even extensions.

    The oscillation is then
    $
      cos((n pi) / L c (t + P_n)) = & cos((n pi) / L c t) \
                              P_n = & (2 L) / (n c) \
                              F_n = & (n c) / (2 L) \
                                  = & n / (2 L) sqrt(T / rho)
    $
  ]
]

== Summary
/ Heat Eq.: $u_t = alpha^2 u_(x x)$.
/ Wave Eq.: $u_(t t) = c^2 u_(x x)$.
/ Laplace's Eq.: $u_(x x) + u_(y y) = 0$.
  - Distribution on a 2D plane: $u_t = alpha^2 (u_(x x) + u_(y y))$.
  - 2D plane with damping: $u_(t t) + gamma u_t = c^2 (u_(x x) + u_(y y))$.
  #solution[
    - $
                  u(x, y) = & e^(i k x + sigma y) \
        u_(x x) + u_(y y) = & [(i k)^2 + sigma^2] e^(i k x + sigma y) \
                          = & 0 \
                    sigma = & plus.minus k.
      $
    - $
        u(x, y) = & e^(i k x) e^(plus.minus k y) \
                = & e^(plus.minus k x) e^(i k y).
      $
  ]

#problem[
  Given four boundary conditions for a Laplace's equation:
  $
    u_(x x) + u_(y y) = & Delta u \
              u(x, 0) = & f^"S" (x) \
              u(x, b) = & f^"N" (x) \
              u(0, y) = & f^"W" (x) \
              u(a, y) = & f^"E" (x),
  $
  give $u(x, y)$.

  #solution[
    Since derivation is a linear operation, we can split the problem into four parts:
    $
      Delta u^"N" = Delta u^"E" = Delta u^"S" = Delta u^"W" = & 0 \
                              u^"N" + u^"E" + u^"S" + u^"W" = & u.
    $

    #important-box[
      Be very familiar with hyperbolic trigonometry identities.
    ]

    - The case of $Delta u^"N" = 0$:
      $
                     u^"N" (x, y) = & X(x) Y(y) \
        X''(x) Y(y) + X(x) Y''(y) = & 0 quad "boundaries depend on" x \
                  (X''(x)) / X(x) = & - (Y''(y)) / Y(y) \
                                  = & -mu^2. quad "setup for the" X "solution"
      $
      For $X$,
      $
        X''(x) + mu^2 X(x) = & 0 \
               X(0) = X(a) = & 0 \
                      mu_n = & (n pi) / a \
                   X_n (x) = & sin((n pi x) / a).
      $
      For $Y$,
      $
          Y''(y) - mu^2 Y(y) = & 0 \
                           Y = & e^(r y) \
        (r^2 - mu^2) e^(r y) = & 0 \
                           r = & plus.minus mu \
                        Y(y) = & c_1 e^(mu y) + c_2 e^(-mu y) \
                             = & A cosh(mu y) + B sinh(mu y) \
              Y(0) = 0 implies & A = 0 \
                        Y(y) = & B sinh(mu y).
      $
      Write them into a Fourier Sine Series,
      $
                    u^"N" (x, y) = & sum_(n = 1)^oo B_n sinh((n pi y) / a) sin((n pi x) / a) \
        f^"N" (X) = u^"n" (x, b) = & sum_(n = 1)^oo B_n sinh((n pi b) / a) sin((n pi x) / a) \
          B_n sinh((n pi b) / a) = & 2 / a integral_(0)^(a) f^"N" (x) sin((n pi x) / a) dd(x) \
                             B_n = & (f^"N"_n) / sinh((n pi b) / a) \
                    u^"N" (x, y) = & sum_(n = 1)^oo f^"N"_n sinh((n pi y) / a) / sinh((n pi b) / a) sin((n pi x) / a) \
      $

    - The case of $Delta u^"E" = 0$:
      Swap symbols from $u^"N" (x, y)$:
      $
        u^"E" (x, y) = & sum_(n = 1)^oo f^"N"_n sinh((n pi x) / b) / sinh((n pi a) / b) sin((n pi y) / b).
      $

    - The case of $Delta u^"W" = 0$:
      $
                     u^"W" (x, y) = & X(x) Y(y) \
        X''(x) Y(y) + X(x) Y''(y) = & 0 quad "boundaries depend on" y \
                  (X''(x)) / X(x) = & - (Y''(y)) / Y(y) \
                                  = & mu^2. quad "setup for the" Y "solution"
      $

      For $Y$,
      $
              ... \
        Y_n (y) = & sin((n pi y) / b).
      $

      For $X$,
      $
        X''(x) - mu^2 X(x) = & 0 \
        X(x) = & A cosh(mu x) + B sinh(mu x) \
        = & C sinh(mu (a - x)) \
        X(a) = 0 implies & B = - (A cos(mu a)) / sinh(mu a) \
        X(x) = & A / sinh(mu a) [sinh(mu a) cosh(mu x) - cosh(mu a) sinh(mu x)] \
        = & A / sinh(mu a) sinh(mu (a - x)) \
        = & C sinh(mu (a - x)) \
        u^"W" (x, y) =& sum_(n = 1)^oo C_n sinh((n pi) / b (a - x)) sin((n pi y) / b) \
        f^"W" (y) = u^"W" (0, y) =& sum_(n = 1)^oo C_n sinh((n pi a) / b) sin((n pi y) / b) \
        C_n sinh((n pi a) / b) =& 2 / b integral_(0)^(b) f^"W" (y) sin((n pi y) / b) dd(y) \
        C_n f^"W"_n / sinh((n pi a) / b) \
        u^"W" (x, y) =& sum_(n = 1)^oo f^"W"_n sinh((n pi (a - x)) / b) / sinh((n pi a) / b) sin((n pi y) / b).
      $

    - The case of $Delta u^"S" = 0$:
      Swap symbols from $u^"W" (x, y)$:
      $
        u^"S" (x, y) = & sum_(n = 1)^oo f^"S"_n sinh((n pi (b - y)) / a) / sinh((n pi b) / a) sin((n pi x) / a).
      $
  ]
]

#problem(title: [Another Neumann Boundary Condition])[
  Given an $a$ for $x$ and a $b$ for $y$,
  $
                                Delta u = & 0 \
    pdv(u, x) (0, y) = pdv(u, x) (a, y) = & 0 \
                       pdv(u, y) (x, 0) = & f(x) \
                       pdv(u, y) (x, b) = & 0.
  $
  Additionally, $f'(x)$ should be zero, because of physics.

  #solution[
    $
      Delta u = & pdv(u, x, 2) + pdv(u, y, 2).
    $
    Notice that
    $
      pdv(u, x) (0, y) = pdv(u, x) (a, y) = & 0
    $
    is a homogeneous boundary condition, hence we can seperate variables.
    $
                          u(x, y) = & X(x) Y(y) \
      pdv(u, x, 2) + pdv(u, y, 2) = & X''(x) Y(y) + X(x) Y''(y) \
                                  = & 0 \
                  (X''(x)) / X(x) = & - (Y''(y)) / Y(y) \
                                  = & -mu^2.
    $
    (The homogeneous boundary condition is in the $x$ direction, which is why we choose to make $-mu^2$ instead of $mu^2$.)
    $
      pdv(u, x) (0, y) = & X'(0) Y(y) quad & "always true" \
                 X'(0) = & 0.
    $
    For $X$,
    $
      X''(x) + mu^2 X(x) = & 0 \
           X'(0) = X'(a) = & 0 \
                    mu_n = & (n pi) / a quad    & n in {0, 1, 2, ...} \
                 X_n (x) = & cos((n pi x) / a).
    $
    For $Y$,
    $
      Y''(y) - mu^2 Y(y) = & 0 \
                   Y'(b) = & 0 \
                    Y(y) = & A cosh(mu y) + B sinh(mu y) \
                         = & C cosh(mu (b - y)),
    $
    which can be given by
    $
      Y'(b) = & A mu sinh(mu b) + B mu cosh(mu b) \
            = & 0 \
          B = & - (A sinh(mu b)) / cosh(mu b) \
       Y(y) = & A / cosh(mu b) [cosh(mu b) cosh(mu y) - sinh(mu b) sinh(mu y)] \
            = & underbrace(A / cosh(mu b), C) cosh(mu (b - y)).
    $

    $
      u(x, y) = & C_0 + sum_(n = 1)^oo C_n cosh(mu_n (b - y)) cos(mu_n x) \
      pdv(u, y) (x, y) = & 0 + sum_(n = 1)^oo -C_n mu_n sinh(mu_n (b - y)) cos(mu_n x) \
      f(x) = & 0 - sum_(n = 1)^oo C_n mu_n sinh(mu_n b) cos((n pi x) / a) \
      = & a_0 / 2 + sum_(n = 1)^oo a_n cos((n pi x)/ L) \
      a_0 = & 2 / a integral_(0)^(a) f(x) dd(x) \
      = & 0 \
      -C_n mu_n sinh(mu_n b) = & 2 / a integral_(0)^(a) f(x) cos((n pi x) / a) dd(x) \
      = & a_n^f \
      C_n = & - a_n^f / (mu_n sinh(mu_n b)) \
      u(x, y) = & C_0 - sum_(n = 1)^oo (a_n^f cosh((n pi) / a (b - y)) cos((n pi x) / a)) / ((n pi) / a sinh((n pi b) / a)).
    $
  ]
]

#problem(title: [Mixed Boundary Conditions])[
  The previous setup, but the left $x$ boundary is
  $
    pdv(u, x) (0, y) = & 0,
  $
  and the bottom boundary is
  $
    pdv(u, y) (x, 0) = & sin((3 pi x) / (2 a)).
  $

  #solution[
    ...still choose $-mu^2$ since the homogeneous boundary is in the $x$ direction.

    For $X$,
    $
      X(0) = X'(a) = & 0.
    $
    - If $mu = 0$,
      $
        X''(0) = X'(0) = & 0,
      $
      trivial.
    - If $mu > 0$,
      $
                   X(x) = & A cos(mu x) + B sin(mu x) \
                  X'(x) = & -A mu sin(mu x) + B mu cos(mu x) \
         X(0) = 0 implies & A = 0 \
        X'(a) = 0 implies & mu a = (?) pi / 2 \
                 mu_n a = & (2n - 1) pi / 2 \
                   mu_n = & ((2n - 1) pi) / (2a) quad        & n in {1, 2, ...} \
                X_n (x) = & sin(mu_n x).
      $
    // TODO somehow get Y
  ]
]
