#import "../lib.typ": *
#show: setup.with(
  title: [MATH 256 _Differential Equations_],
  author: "Yecheng Liang",
)

#set math.vec(delim: "[")
#set math.mat(delim: "[")

#let oL = math.op[L]

= Differential Equations
#definition(title: [Differential Equation])[
  An equation that defines a function by giving a relationship between the function and its derivative.
]

#example[
  $
    y' + y = x.
  $
]

Integration is solving a trivial differential equation.

Given a first-order, linear differential equation, $dv(y, x) = a y$, a reasonable guess is $y = A e^(a x)$.
We can take any constant $A$ because the equation is linear.

== Seperable Equations Method
For non-linear differential equations, we would manipulate the equation so one side is expressed by $y$, the other by $x$ and $dd(x)$.
Then, integrating both sides gives us a relationship between $x$ and $y$.

#example[
  $
              dv(y, x) & = a y \
             dd(y) / y & = a dd(x) \
    integral dd(y) / y & = a integral dd(x) + C \
             ln abs(y) & = a x + C \
                     y & = e^(ln(abs(y))) \
                       & = e^(a x + C) \
                       & = e^c e^(a x) \
                       & = A e^(a x).
  $
]

== Integrating Factor Method
With a linear first-order equation, we can forcibly express it by only $x$.

Let $oL$ be an operator such that
$
  oL y & = (dv(, x) + p(x)) y \
       & = dv(y, x) + p(x) y \
       & = g(x).
$
So long as $p(x), g(x)$ are continuous, a solution exists.
And, if $oL y = 0$, we say the equation is homogeneous.

Let $F(x)$ be the _integrating factor_ such that
$
  F(x) dv(y, x) + F(x) p(x) y & = dv(, x) [F(x) y].
$
From the equatoion above we can see that, if we differentiate $F(x)$, we get itself multiplied by $p(x)$, looks much like our guess of exponential before.
Hence,
$
  F(x) & = e^(integral p(x) dd(x)).
$

Multiply $oL y$ by $F(x)$,
$
  e^(integral p(x) dd(x)) dv(y, x) + e^(integral p(x) dd(x)) p(x) y & = e^(integral p(x) dd(x)) g(x)
$
Notice that the LHS is differential of a product.
$
  dv(, x) [e^(integral p(x) dd(x)) y] & = e^(integral p(x) dd(x)) g(x) \
            e^(integral p(x) dd(x)) y & = integral e^(integral p(x) dd(x)) g(x) dd(x) + C \
                                    y & = e^(-integral p(x) dd(x)) (integral e^(integral p(x) dd(x)) g(x) dd(x) + C).
$

#problem[
  Solve
  $
    cases(
      oL y = y' + y = x,
      y(0) = 1
    )
  $

  #solution[
    Using the integral factor form, let
    $
       p(x) & = 1 \
       y(x) & = x \
      y'(x) & = 1.
    $
    Thus, we find the integrating factor to be
    $
      F(x) & = e^(integral p(x) dd(x)) \
           & = e^x.
    $
    Then, transform the equation by multiplying $F(x) = e^x$ to both sides.
    $
      e^x y' + e^x y & = [e^x y]' \
                     & = x e^x.
    $
    Notice that the LHS is differential of a product, undo the chain rule, we get
    $
      e^x y & = e^x x - e^x + C.
    $
    Don't forget the $C$ generated by the integrating both sides.

    Move the factor of integration to the RHS,
    $
      y & = x - 1 + C e^(-x)
    $
    Plug in $y(0) = 1$,
    $
      y(x) = x - 1 + 2e^(-x).
    $
  ]
]

#problem[
  Solve
  $
    oL y & = y' + y = sin(x).
  $

  #solution[
    Recall Euler's Equation,
    $
      e^(i x) = cos(x) + i sin(x).
    $

    Similar to the previous problem,
    $
          F(x) & = e^x oL y \
               & = [e^x y]' \
               & = e^x sin(x) \
      [e^x y]' & = Im e^((1 + i)x).
    $
    Integrate both sides,
    $
      e^x y & = Im e^((1 + i)x) / (1 + i) + C.
    $
    Turn the fraction term of RHS into proper form,
    $
      e^((1 + i)x) / (1 + i) & = (e^((1 + i)x) (1 - i)) / ((1 + i) (1 - i)) \
                             & = (e^((1 + i)x) (1 - i)) / 2.
    $
    Continue with the factor of integration method,
    $
      y & = Im (e^((1 + i)x) (1 - i) e^(-x)) / 2 + C e^(-x) \
        & = Im (e^(i x) (1 - i)) / 2 + C e^(-x) \
        & = Im ((cos(x) + i sin(x)) (1 - i)) / 2 + C e^(-x) \
        & = Im ((cos(x) - i^2 sin(x)) + (i sin(x) - i cos(x))) / 2 + C e^(-x) \
        & = Im ((cos(x) + sin(x)) + i (sin(x) - cos(x))) / 2 + C e^(-x) \
        & = (sin(x) - cos(x)) / 2 + C e^(-x).
    $
    No particular solution.
  ]
]

== Undetermined Coefficient Method
For a homogeneous linear equatoion, we can guess a particular solution, $y_p$.
- If $g(x) = x^n$, then $y_p = a_n x^n + a_(n-1) x^(n-1) + ... + a_1 x + a_0$.
- If $g(x) = e^(a x)$, then $y_p = A e^(a x)$.
- If $g(x) = sin(x) "or" cos(x)$, then $y_p = A cos(x) + B sin(x)$.
The guesses are linear combinations of all possible derivatives of $g(x)$.

The particular solution still carries undetermined coefficients.
Assume this $y_p$ to transform $oL y$.

